Repository viur-framework/viur-core, pull requests merged in 2020-06, with the labels that each got.

#22 ratelimit.py - determinate IP: Use the network identifier, and not the interface.
  ratelimit.py
Labels: bug, typo

#30 fixed bug in updateRelations
  skeleton.py
Labels: bug

#20 SkeletonInstance.__iter__() and SkeletonInstance.__getValues__() incl. type annotations
  skeleton.py
Labels: enhancement

#31 Pass the cursor to skellist again
  db.py
Labels: bug

#32 Fixed calling deferred tasks inside transactions
  db.py
  tasks.py
Labels: bug
