Repository viur-framework/viur-core, pull requests merged in 2020-10, with the labels that each got.

#132 query.Get() is now query.getEntry()
  prototypes/tree.py
Labels: bug

#133 Strip username on login of whitespaces; replacement for #129 with skel.fromClient removed
  modules/user.py
Labels: enhancement

#138 Fixed performMagic call in formmailer
  modules/formmailer.py
Labels: bug

#139 Use utcNow() in account creation by login with google
  modules/user.py
Labels: bug

#140 Re-Added ensureOwnModuleRootNode helper function to tree-prototype
  prototypes/tree.py
Labels: enhancement

#141 fixed a few bugs in tree.py code, passing key obj instead of strings etc
  prototypes/tree.py
Labels: bug

#145 Change notation for relationBone in renderBoneValue of html render
  render/html/default.py
Labels: enhancement

#130 added backwards compatibility to recordBone singleValueUnserialize method
  bones/recordBone.py
Labels: discussion

#150 Allow up to 4kb in credentialBone (needed for JTWs)
  bones/credentialBone.py
Labels: bug, enhancement

#149 Renamed remaining amount paramenters to limit
  bones/randomSliceBone.py
  bones/spatialBone.py
  db.py
Labels: enhancement

#135 Don't add empty values to bones that are multiple
  bones/bone.py
Labels: bug

#147 Feature/hooks before actions
  prototypes/list.py
  prototypes/singleton.py
  prototypes/tree.py
Labels: enhancement

#148 fixed dateBone(time = True, date = False)
  bones/dateBone.py
Labels: bug
