Repository viur-framework/viur-core, pull requests merged in 2020-07, with the labels that each got.

#36 Fixed isinstance-tests for skeletons in jinja2 render
  render/html/default.py
Labels: bug

#37 added args to html-render logging function to support formatstring
  render/html/env/debug.py
Labels: enhancement

#38 Allow setting relationalBones back to empty
  bones/relationalBone.py
Labels: bug

#43 Fixed ordering by relational properties (if the relation is multiple)
  bones/relationalBone.py
  db.py
Labels: bug

#42 Restored fulltext search functionality
  bones/bone.py
  bones/numericBone.py
  bones/relationalBone.py
  bones/stringBone.py
  bones/textBone.py
  customdatabases.py
  skeleton.py
Labels: bug

#40 Deferr tasks to the end of the current request instead of calling them inline
  request.py
  tasks.py
Labels: bug

#44 Fixing error 500 in /user/login call, again
  render/html/user.py
Labels: bug

#41 Added a lockEmpty property to UniqueValue
  bones/bone.py
  modules/user.py
Labels: bug, enhancement

#39 Standardize several notations, part 1: Renaming add/edit/delete-events and rendering functions
  modules/file.py
  modules/formmailer.py
  modules/user.py
  prototypes/hierarchy.py
  prototypes/list.py
  prototypes/singleton.py
  prototypes/tree.py
  prototypes/uniformtree.py
  render/html/default.py
  render/json/default.py
  render/xml/default.py
  tasks.py
Labels: enhancement

#33 Fixed reference to currentRequest. Replaces #26
  prototypes/uniformtree.py
Labels: bug

#45 Correctly set creation/change-Date on local development server
  bones/dateBone.py
Labels: bug

#47 Added kind attribute to renders. Fixes #23
  render/admin/__init__.py
  render/html/default.py
  render/json/default.py
  render/vi/__init__.py
  render/xml/default.py
Labels: enhancement

#46 Futher fixes for Deferred Tasks. Replacement for #35
  tasks.py
Labels: bug

#48 Feature/rename db get
  db.py
  dbtransfer.py
  modules/file.py
  modules/order_paypal.py
  modules/user.py
  render/html/env/viur.py
  utils.py
Labels: enhancement

#53 Hotfixing query.get() which is now query.getEntry()
  prototypes/list.py
Labels: bug, hotfix

#49 Feature/remove obsolete prototypes
  bones/__init__.py
  bones/fileBone.py
  bones/hierarchyBone.py
  bones/treeItemBone.py
  bones/treeLeafBone.py
  bones/treeNodeBone.py
  modules/file.py
  prototypes/__init__.py
  prototypes/hierarchy.py
  prototypes/tree.py
  prototypes/uniformtree.py
  render/html/default.py
  render/json/default.py
Labels: enhancement

#50 Whole set of resolved bugs/pending fixme's
  bones/relationalBone.py
  bones/textBone.py
  db.py
  render/html/default.py
  render/json/default.py
  skeleton.py
  tasks.py
Labels: bug

#52 Moved the fulltext search adapter back to skeleton and auto-attach it…
  customdatabases.py
  skeleton.py
Labels: enhancement

#55 fixed some problems with tasks and improved some loggings
  tasks.py
Labels: bug, enhancement

#56 added exception for periodic decorated methods with leading underscore
  tasks.py
Labels: enhancement

#54 fixed request/site caching
  cache.py
Labels: bug, enhancement

#28 added move function for Uniform Tree
  prototypes/tree.py
Labels: enhancement

#1 add missing necessary refKeys instead of raising an error
  bones/fileBone.py
  bones/relationalBone.py
Labels: enhancement

#51 Fixed / unified cursors
  db.py
  modules/order.py
  render/json/default.py
  securitykey.py
  session.py
  skeleton.py
Labels: bug, enhancement

#62 Subskel fix
  skeleton.py
Labels: bug

#58 fixed tasks in modules/file
  modules/file.py
Labels: bug, enhancement

#66 Fixed skelstructure failing when processing an relationalBone
  render/html/default.py
Labels: bug

#60 Added support for multiple tasks with the same name in the same file …
  tasks.py
Labels: bug, enhancement

#69 Fixed several isinstance-tests in render/html/env/viur
  render/html/env/viur.py
Labels: bug

#65 Fixing _tasks/list
  render/json/default.py
  skeleton.py
  tasks.py
Labels: bug

#63 Make unique session cookies
  session.py
Labels: enhancement, proposal

#75 Fixed db.filterHook having only partial effect
  db.py
Labels: bug

#73 Fixing subSkel behavior to be ViUR2 compliant
  skeleton.py
Labels: discussion

#76 subfield must always be parsed if a relSkel is defined even if it is not multiple
  bones/relationalBone.py
Labels: bug

#77 Fixing AttributeError in json-renderer
  render/json/default.py
Labels: bug

#74 Fix/user login
  modules/user.py
  render/html/user.py
  render/json/user.py
  template/editform_bone_color.html
  template/editform_bone_numeric.html
  template/editform_bone_password.html
  template/editform_bone_str.html
Labels: bug

#70 Fixed db.Query.clone()
  db.py
Labels: bug

#80 Support key-objects in deferred tasks
  tasks.py
Labels: bug, enhancement

#84 Fix cloning skeleton-instances with data
  skeleton.py
Labels: bug

#82 TypeError: isinstance() arg 2 must be a type or tuple of types
  bones/relationalBone.py
Labels: bug

#85 Fixing performMagic on userBone
  bones/userBone.py
Labels: bug

#86 Prevent a bone from beeing multiple and having creation or updateMagic set
  bones/dateBone.py
  bones/userBone.py
Labels: bug, enhancement

#87 Fixed canAccess beeing ignored as they where not mapped to mainResolver
  __init__.py
Labels: bug, security

#89 user vi renderer delivers the wrong kind
  render/vi/user.py
Labels: bug

#88 Fix/time zone handling
  bones/dateBone.py
  i18n.py
  render/html/env/date.py
Labels: bug, enhancement
