Repository viur-framework/viur-core, pull requests merged in 2020-11, with the labels that each got.

#157 handling nomissing param in edit as in add
  render/html/default.py
Labels: bug

#156 fixing regression with UserPassword.verify and registrationEmailVerif…
  modules/user.py
  securitykey.py
Labels: bug

#155 Update request.py
  request.py
Labels: enhancement

#136 Fixes for i18n / multilanguage support
  bones/numericBone.py
  bones/relationalBone.py
  bones/stringBone.py
  bones/textBone.py
  i18n.py
  render/html/default.py
Labels: bug, discussion

#158 Fixing UserPassword.recover draft
  modules/user.py
Labels: bug

#137 Push /file/download requests into the ede caches …
  modules/file.py
  render/html/env/viur.py
Labels: enhancement

#160 Implement RebuildSearchIndexTask with QueryIter and remove not-implemented compact-mode
  skeleton.py
Labels: documentation, enhancement

#163 textBones are no longer indexed by default
  bones/textBone.py
Labels: enhancement

#162 Fixed injectDownloadURL in file skel
  modules/file.py
Labels: bug

#161 [Breaking] Fixed reporting of errors to Vi/Admin
  bones/bone.py
  bones/captchaBone.py
  bones/colorBone.py
  bones/credentialBone.py
  bones/dateBone.py
  bones/numericBone.py
  bones/passwordBone.py
  bones/relationalBone.py
  bones/selectBone.py
  bones/spatialBone.py
  bones/stringBone.py
  bones/textBone.py
  modules/user.py
  render/admin/__init__.py
  render/json/default.py
  skeleton.py
Labels: bug
