Repository viur-framework/viur-core, pull requests merged in 2021-05, with the labels that each got.

#279 Remove obsolete method getAvailableRootNodes__ in modules.file
  core/modules/file.py
Labels: Priority: Low

#276 Add support to derive Index-module from BasicApplication
  core/__init__.py
Labels: enhancement

#281 Fixed removing viur-relations objects in relationalBole:postDeletedHandler
  core/bones/relationalBone.py
Labels: bug, hotfix

#283 Fixed flushCache key-access
  core/cache.py
Labels: bug
