Repository viur-framework/viur-core, pull requests merged in 2021-06, with the labels that each got.

#256 Implemented a new password recovery process
  core/modules/user.py
Labels: enhancement, security

#288 Fixed queries with a limit > 300
  core/db.py
Labels: bug

#287 Updated dependencies to latest versions
  requirements.txt
Labels: security

#286 Temp. disable the changelist evaluation in updateRelations
  core/skeleton.py
Labels: bug

#289 This avoid infinity queries due to a wrong new cursor
  core/db.py
Labels: enhancement

#291 Correctly set Max-Age on the session-cookie according to its lifetime
  core/session.py
Labels: bug

#295 Copy the key if an entity is copied in db.fixUnindexableProperties
  core/db.py
Labels: bug

#292 Allow setting a default expiration for downloadUrlFor, added docstrings
  core/config.py
  core/render/html/env/viur.py
  core/utils.py
Labels: documentation, enhancement

#285 Fixed re-deferring in deferred calls
  core/tasks.py
Labels: bug

#284 Added first support for the dbaccelerator (faster get_multi)
  core/db.py
Labels: bug, dependencies

#294 Deprecate collectSkelData and removed it's usage
  core/render/html/default.py
  core/render/html/env/viur.py
  core/render/html/user.py
Labels: bug

#297 Fixed accessing bone-values in renderEditBone
  core/render/html/env/viur.py
Labels: bug

#305 Fixed viur-tags search with multiple words, fixed it's sort-order
  core/skeleton.py
Labels: bug
