Repository viur-framework/viur-core, pull requests merged in 2021-04, with the labels that each got.

#252 Added a mutal redirect between Vi and Admin if either one is not available; Fixed non-https redirect for Vi
  core/render/__init__.py
  core/render/admin/__init__.py
  core/render/vi/__init__.py
Labels: bug, enhancement

#253 Ensure that skel.fromClient is never valid if no values are submitted
  core/skeleton.py
Labels: bug

#257 Hash passwords in passwordBone early on (in fromClient)
  core/bones/passwordBone.py
  core/render/html/default.py
  core/render/json/default.py
  core/render/xml/default.py
Labels: Priority: High, bug, security

#255 Added support for form-action in CSP and set it by default to self
  core/config.py
  core/securityheaders.py
Labels: enhancement, security

#248 Fixed google-api-core dependency, added tzlocal
  requirements.txt
Labels: bug, enhancement

#249 Correctly restore utils.getCurrentUser()["key"] in deferred tasks
  core/tasks.py
Labels: bug

#250 Feature/support trusted types
  core/config.py
  core/securityheaders.py
Labels: enhancement, security

#251 Feature/enhanced security headers
  core/__init__.py
  core/config.py
  core/request.py
  core/securityheaders.py
Labels: enhancement, security

#254 Allow setting default-credentials for the captcha-bone in viur.config
  core/bones/captchaBone.py
  core/config.py
Labels: enhancement

#263 Add + to the list of allowed characters for Mimetypes (for image/svg+xml)
  core/modules/file.py
Labels: bug

#262 Fixed setBoneValue in relationalBone (xor is not defined if one parameter is None)
  core/bones/relationalBone.py
Labels: bug

#264 Fixed setBoneValue in baseBone
  core/bones/bone.py
Labels: bug

#268 Fixed thumbnail deriver, changed output filename
  core/modules/file.py
Labels: bug

#270 Fixed unserializing of booleanBones that are False
  core/bones/bone.py
Labels: bug

#272 Fixed resolving of google-api-core
  requirements.txt
Labels: bug

#274 Correct the naming of the ISO2->ISO3 country maps in selectCountryBone
  core/bones/selectCountryBone.py
Labels: Priority: Low, typo
