Repository viur-framework/viur-core, pull requests merged in 2021-02, with the labels that each got.

#190 Reworked file and derived handling
  bones/fileBone.py
  bones/relationalBone.py
  modules/file.py
  render/html/env/viur.py
  tasks.py
  utils.py
Labels: bug

#191 Fixed a race condition when validating skeys (XSRF-Tokens)
  session.py
Labels: bug

#194 Ensure a valid limit is set in queries containing an IN filter
  db.py
Labels: bug

#195 Feature/email support
  config.py
  email.py
  errors.py
  render/html/default.py
  tasks.py
  utils.py
Labels: enhancement

#24 generally overworked the sendEmail method and the according render method
  errors.py
  render/html/default.py
  utils.py
Labels: documentation, enhancement
