Repository viur-framework/viur-core, pull requests merged in 2021-03, with the labels that each got.

#208 Fix currentLanguage in i18n and tasks
  i18n.py
  tasks.py
Labels: Priority: High, bug

#204 Prevent add/delete etc being called on a skeleton if an outputrender is attached
  skeleton.py
Labels: bug

#203 Added the yieldBoneValues to SkeletonInstance.items() to allow iterating key-value pairs
  skeleton.py
Labels: enhancement

#202 Made the json-render aware of our translation-class
  render/admin/__init__.py
  render/json/default.py
  render/vi/__init__.py
Labels: Priority: Medium, bug, enhancement

#200 Fixed imports of the sendEmailToAdmins function
  __init__.py
  dbtransfer.py
  modules/user.py
  tasks.py
Labels: Priority: High, bug

#205 Ported cache tracking feature from server
  cache.py
  db.py
  prototypes/list.py
  prototypes/singleton.py
  prototypes/tree.py
  request.py
  skeleton.py
Labels: enhancement

#219 Raise NotFound if no entry was found in list-protypes edit
  prototypes/list.py
Labels: Priority: Low, bug

#215 Initialize the default-value to a list if defaultValue is None and the bone is multiple
  bones/bone.py
Labels: bug

#210 Feature/unicode normalisation
  request.py
Labels: bug, enhancement, security

#152 Add rawValueBone
  bones/__init__.py
  bones/bone.py
  bones/rawValueBone.py
Labels: enhancement

#220 Add support to use a task queue emulator
  tasks.py
Labels: Priority: Medium, enhancement, proposal

#232 Import RelationalConsistency in bone/__init__
  core/bones/__init__.py
Labels: enhancement

#229 Added a simple QueryIter to tasks which deletes all entities encountered
  core/email.py
  core/tasks.py
Labels: enhancement

#225 Fixed the email-api call in modules/formmailer.py
  core/modules/formmailer.py
Labels: bug

#231 Ensure the current projectid is whitelisted in conf["viur.validApplicationIDs"]
  core/__init__.py
  core/config.py
Labels: enhancement

#227 Added redirect for the admin wasm interface
  core/render/admin/__init__.py
Labels: enhancement

#123 Started to generialize setBoneValue to handle multiple and languages
  core/bones/bone.py
  core/bones/relationalBone.py
  core/bones/stringBone.py
  core/bones/textBone.py
Labels: Priority: Medium, bug, enhancement

#230 Fixed the ratelimit module
  core/ratelimit.py
Labels: bug

#228 Added a RequestValidator to request.py
  core/request.py
Labels: enhancement, security

#224 Removed obsolete functions on db.Query
  core/db.py
Labels: bug

#223 Split view/structure into a seperate function
  core/prototypes/list.py
  core/prototypes/singleton.py
  core/prototypes/tree.py
Labels: enhancement

#214 First draft for evaluating typehints in exposed functions
  core/request.py
Labels: enhancement

#236 Fixed performMagic function in userBone when called in an unauthenticated request
  core/bones/userBone.py
Labels: bug

#239 Fixed a type-annotation from tuple to typing.Tuple in request.py:processTypeHint
  core/request.py
Labels: bug

#238 Fixed the call to sendEmail in modules/user.py:UserPassword
  core/modules/user.py
Labels: bug

#246 Allow uploads with mimetypes containing digits (video/mp4)
  core/modules/file.py
Labels: bug

#244 Added a requirements.txt with pinned verion numbers and hashes
  requirements.txt
Labels: enhancement

#243 Limit the scope of typeerrors which we raise NotAcceptable for
  core/request.py
Labels: bug

#242 Recreate the weak file entries on import from ViUR2
  core/bones/fileBone.py
Labels: bug

#241 Pass the loginFailed flag and the accountstatus to login_template in jinja2 render
  core/modules/user.py
  core/render/html/user.py
Labels: bug, enhancement

#237 Fixed choosing another default (=top-level) render aside from html
  core/__init__.py
Labels: bug

#247 Fixed sending the password recovery email
  core/modules/user.py
  core/skeleton.py
Labels: bug
