Repository viur-framework/viur-core, pull requests merged in 2022-11, with the labels that each got.

#540 Add workflow of GitHub-Action for linting
  .github/workflows/pep8.yaml
Labels: feature, Priority: Medium, ci/cd

#539 Extend linter config
  .pep8speaks.yml
  Pipfile
  Pipfile.lock
  setup.cfg
  tox.ini
Labels: Priority: Medium

#545 Remove context from `git show`/`git diff` for linting
  .github/workflows/pep8.yaml
  Pipfile
Labels: ci/cd

#533 Accept variations parameters with bool type hints
  core/bones/boolean.py
  core/config.py
  core/request.py
Labels: refactoring

#547 Improve `utils.sanitizeFileName` to quote non-ASCII
  core/utils.py
Labels: hotfix

#528 Rewrite `getReferencedBlobs` and `getSearchTags`
  core/bones/base.py
  core/bones/file.py
  core/bones/numeric.py
  core/bones/record.py
  core/bones/relational.py
  core/bones/string.py
  core/bones/text.py
Labels: feature, refactoring

#548 Remove `skey == ""` check from add/edit methods.
  core/modules/user.py
  core/prototypes/list.py
  core/prototypes/singleton.py
  core/prototypes/tree.py
  core/tasks.py
Labels: bug, invalid

#554 Fix linter GitHub Action workflow
  .github/workflows/pep8.yaml
Labels: bug, ci/cd

#511 Make it possible that multiple languages could be required
  core/bones/base.py
  core/skeleton.py
Labels: feature

#561 relationalBone-updateLevel-Enum-fix
  core/bones/relational.py
Labels: hotfix

#556 Add is_deferred flag to currentRequest
  core/request.py
  core/tasks.py
Labels: feature

#549 Don't translate name for HTTP Reason Phrase
  core/errors.py
  core/request.py
Labels: bug, invalid

#552 Default disable `viur.render.json.downloadUrlExpiration` and `viur.downloadUrlFor.expiration`
  core/config.py
  core/modules/file.py
  core/render/html/env/viur.py
Labels: discussion, proposal

#562 Move variables to config
  core/__init__.py
  core/bones/captcha.py
  core/bones/date.py
  core/config.py
  core/db.py
  core/email.py
  core/i18n.py
  core/logging.py
  core/modules/file.py
  core/modules/user.py
  core/render/admin/__init__.py
  core/render/html/env/viur.py
  core/render/vi/__init__.py
  core/request.py
  core/session.py
  core/tasks.py
  core/utils.py
Labels: feature, refactoring

#551 Add ModuleConfig with settings for vi
  core/__init__.py
  core/config.py
  core/languages/de.py
  core/modules/moduleconf.py
  core/render/json/user.py
  core/render/vi/__init__.py
Labels: feature, Priority: Low

#567 Implement conf-dict as Conf-class
  core/config.py
  core/render/admin/__init__.py
  core/render/vi/__init__.py
  core/render/xml/__init__.py
  core/utils.py
Labels: feature, refactoring
