Repository viur-framework/viur-core, pull requests merged in 2022-03, with the labels that each got.

#366 Correct the response status code
  core/request.py
Labels: bug, Priority: Medium

#365 Allow configuring the expiration of downloadURLs generated by JSON render
  CHANGELOG.md
  core/config.py
  core/render/json/default.py
Labels: enhancement

#369 Disolved the redirect method in request.py
  core/request.py
Labels: bug

#375 added PyPI packaging
  .github/workflows/publish.yml
  .gitignore
  Pipfile
  Pipfile.lock
  core/modules/user.py
  core/request.py
  core/resources/css/error/error.css
  core/resources/css/reset.css
  core/resources/icons/viur_logo.png
  core/resources/images/beta_small.png
  core/resources/images/vi_app_logo.png
  core/resources/js/viur-forms.js
  core/resources/meta/favicon.ico
  core/resources/meta/favicon.png
  core/resources/meta/humans.txt
  core/resources/meta/viur-apple-touch-icon-114x114-precomposed.png
  core/resources/meta/viur-apple-touch-icon-144x144-precomposed.png
  core/resources/meta/viur-apple-touch-icon-57x57-precomposed.png
  core/resources/meta/viur-apple-touch-icon-72x72-precomposed.png
  core/resources/meta/viur-apple-touch-icon-precomposed.png
  core/resources/meta/viur-apple-touch-startup-image-1496x2048.png
  core/resources/meta/viur-apple-touch-startup-image-1536x2008.png
  core/resources/meta/viur-apple-touch-startup-image-320x460.png
  core/resources/meta/viur-apple-touch-startup-image-640x920.png
  core/resources/meta/viur-apple-touch-startup-image-748x1024.png
  core/resources/meta/viur-apple-touch-startup-image-768x1004.png
  core/resources/meta/viur-logo-error.png
  core/resources/meta/viur-opengraph-image.png
  core/resources/meta/viur_micro.gif
  core/skeleton.py
  core/template/editform_bone_bone.html
  core/template/editform_bone_bool.html
  core/template/editform_bone_captcha.html
  core/template/editform_bone_color.html
  core/template/editform_bone_date.html
  core/template/editform_bone_hidden.html
  core/template/editform_bone_numeric.html
  core/template/editform_bone_password.html
  core/template/editform_bone_record.html
  core/template/editform_bone_relational.treeitem.file.html
  core/template/editform_bone_select.html
  core/template/editform_bone_str.html
  core/template/editform_bone_text.html
  core/template/editform_category.html
  core/template/editform_row.html
  core/template/error.html
  core/template/vi_user_google_login.html
  core/utils.py
  pyproject.toml
  setup.cfg
  setup.py
Labels: enhancement, proposal

#374 Updated requirements, fixed logging
  core/logging.py
  requirements.txt
Labels: bug

#401 Fixed unique=True on multiple=True relationalBones
  CHANGELOG.md
  core/bones/bone.py
  core/bones/relationalBone.py
Labels: bug

#400 Feature/viur datastore0.9
  CHANGELOG.md
  core/config.py
  core/db.py
  core/skeleton.py
  requirements.txt
Labels: enhancement

#403 Fixed deferred calls with _countdown set failing when called from a cronjob
  CHANGELOG.md
  core/tasks.py
Labels: bug
