Repository viur-framework/viur-core, pull requests merged in 2022-10, with the labels that each got.

#522 Add bones to __all__
  core/bones/__init__.py
Labels: enhancement

#519 Get project zone from metadata.google.internal
  core/tasks.py
Labels: enhancement

#524 Use skel.refresh() in updateRelations
  core/bones/relational.py
  core/skeleton.py
Labels: enhancement, Priority: Low

#521 Remove default logging handler
  core/logging.py
Labels: enhancement, Priority: Low

#523 Add `RelationalUpdateLevel` (`Enum`)
  core/bones/relational.py
  core/skeleton.py
Labels: enhancement

#525 Enforce python3.10
  .github/workflows/publish.yml
  .github/workflows/python-test.yaml
  .readthedocs.yml
  Pipfile
  Pipfile.lock
  docs/Pipfile
  docs/Pipfile.lock
  requirements.txt
  setup.cfg
  tests/Pipfile
  tests/Pipfile.lock
Labels: dependencies

#527 Remove obsolete methods `getSearchDocumentFields`
  core/bones/record.py
  core/bones/relational.py
  core/bones/text.py
Labels: Priority: Low

#534 Use `.value` of the RelationalUpdateLevel enum in a datastore entity
  core/bones/relational.py
Labels: bug, Priority: High

#512 new derives renderer
  core/modules/file.py
Labels: enhancement

#535 Upgrade read the docs to v2
  .readthedocs.yml
Labels: bug, documentation

#504 Add configuration for pep8speaks to enforce PEP-8-compliant pull request
  .pep8speaks.yml
Labels: ci/cd
