Repository viur-framework/viur-core, pull requests merged in 2022-09, with the labels that each got.

#498 Add valid mime types to the BoneStructure
  core/render/html/default.py
  core/render/json/default.py
  core/render/xml/default.py
Labels: enhancement

#491 Re-enabling translations in VIUR3
  core/__init__.py
  core/errors.py
  core/i18n.py
  core/languages/__init__.py
  core/languages/de.py
  core/languages/en.py
  core/render/json/default.py
  core/request.py
Labels: enhancement

#499 Set new max Value for SortIndexBone
  core/bones/numeric.py
  core/bones/sortindex.py
Labels: bug

#501 Convert TranslationsKey
  core/i18n.py
Labels: hotfix

#497 Extending KeyBone to check given key's existence
  core/bones/key.py
Labels: enhancement

#490 fixed getReferencedBlobs of TextBone
  core/bones/text.py
Labels: bug

#505 Better fieldPath
  core/bones/base.py
Labels: enhancement

#507 Improving SpatialBone bounds checking and use `float` instead of `int`
  core/bones/spatial.py
  core/render/html/default.py
  core/render/json/default.py
  core/render/xml/default.py
Labels: enhancement

#509 Fixed generateOtps function to work on python3
  core/modules/user.py
Labels: bug

#508 Fix UNB Task and add Logging
  core/tasks.py
Labels: bug

#494 Refactoring default renders for HTML/JSON/XML
  core/render/html/default.py
  core/render/json/default.py
  core/render/xml/default.py
Labels: refactoring

#516 Create a new hmac Key if no one is set
  core/__init__.py
Labels: enhancement

#515 Fix broken multi-language relations
  core/bones/file.py
  core/bones/relational.py
Labels: bug
