Repository viur-framework/viur-core, pull requests merged in 2022-12, with the labels that each got.

#573 `import logging` must stay behind other imports in `__init__.py`
  core/__init__.py
Labels: hotfix, Priority: High

#569 Providing datastore index information with modules
  core/__init__.py
  core/render/json/default.py
  core/render/vi/__init__.py
  requirements.txt
  tests/requirements.txt
Labels: feature, Priority: Low

#577 Refactoring ModuleConf
  core/config.py
  core/modules/moduleconf.py
Labels: refactoring

#590 Change path of index.yaml in load_indexes_from_file
  core/__init__.py
Labels: hotfix

#581 Improve the linter workflow: Use error annotations
  .github/workflows/pep8.yaml
  Pipfile
  tox.ini
Labels: Priority: Low, ci/cd

#598 Change usages of new path configs
  core/modules/user.py
  core/render/__init__.py
  core/render/html/default.py
  core/request.py
  core/skeleton.py
Labels: bug, feature, refactoring
