Repository viur-framework/viur-core, pull requests merged in 2022-05, with the labels that each got.

#434 Minor fixes for baseBone and textBone
  CHANGELOG.md
  core/bones/bone.py
  core/bones/textBone.py
  core/version.py
Labels: bug

#433 Add documentation for seo-feature in ViUR
  docs/Makefile
  docs/Pipfile
  docs/Pipfile.lock
  docs/conf.py
  docs/doc_tutorial/advanced/training_seo.rst
Labels: documentation, enhancement

#437 Remove errors.ReadFromClientError
  CHANGELOG.md
  core/errors.py
  core/request.py
Labels: enhancement, Priority: Low

#440 Fixed required=True bones could still be set empty if omitted from the postdata
  CHANGELOG.md
  core/skeleton.py
Labels: bug

#438 Remove the unused cursor parameter in doClearSKeys
  core/securitykey.py
Labels: bug, Priority: Medium

#445 Fix docs logo and improve maintainability of CSS
  docs/conf.py
  docs/rtdtemplate/layout.html
  docs/rtdtemplate/static/css/theme.css
  docs/rtdtemplate/static/css/theme.min.css
  docs/rtdtemplate/theme.conf
Labels: documentation
