Repository viur-framework/viur-core, pull requests merged in 2022-06, with the labels that each got.

#459 Fixed seoKey handling in skeletons and fixed seoURLtoEntry
  CHANGELOG.md
  core/skeleton.py
  core/utils.py
Labels: bug

#455 Added ratelimit to login with username/password
  CHANGELOG.md
  core/modules/user.py
Labels: enhancement, security

#461 Improved logging to cope with the new logviewer
  CHANGELOG.md
  core/logging.py
  core/request.py
Labels: enhancement

#463 Implement `errors.TooManyRequests` exception
  core/errors.py
  core/modules/user.py
  core/ratelimit.py
Labels: enhancement

#457 Add support for `Literal` type annotations in processTypeHint
  core/request.py
Labels: enhancement
