Repository viur-framework/viur-core, pull requests merged in 2023-07, with the labels that each got.

#781 doc: RTD toctree is written properly now
  docs/doc_start/30_myfirstproject.rst
  docs/doc_tutorial/index.rst
  docs/index.rst
Labels: documentation, Priority: Low, refactoring

#746 doc: Improve type hints in sphinx doc
  docs/Pipfile
  docs/Pipfile.lock
  docs/conf.py
  docs/requirements.txt
Labels: documentation, Priority: Low

#639 feat: Add `compute`-feature to `BaseBone`
  core/bones/__init__.py
  core/bones/base.py
  core/skeleton.py
Labels: feature

#788 fix: Extend MetaBaseSkel reserved keywords to "structure"
  core/skeleton.py
Labels: Priority: Low, main

#791 fix: Clone `current.user` for use with Jinja
  core/render/html/env/viur.py
Labels: bug, hotfix, Priority: High, main

#793 fix: Add missing fallback for `NumericBone.refresh()` destroying valid data
  core/bones/numeric.py
Labels: hotfix, Priority: High, main

#785 feat: Compute `creationdate` and `changedate` with the new `compute`-feature
  core/skeleton.py
Labels: Priority: Medium, refactoring

#783 docs: fixed all Auto-API build Errors
  core/bones/captcha.py
  core/bones/color.py
  core/bones/file.py
  core/bones/json.py
  core/bones/relational.py
  core/bones/spatial.py
  core/email.py
  core/module.py
  core/modules/file.py
  core/prototypes/tree.py
  core/render/html/env/viur.py
  core/render/html/utils.py
  core/request.py
  core/securityheaders.py
  core/utils.py
  docs/conf.py
  docs/doc_start/30_myfirstproject.rst
  docs/doc_tutorial/basic/viur_on_windows.rst
Labels: documentation, refactoring

#685 refactor: `singleValueFromClient` with type hints and docstrings
  core/bones/base.py
  core/bones/boolean.py
  core/bones/captcha.py
  core/bones/color.py
  core/bones/credential.py
  core/bones/date.py
  core/bones/email.py
  core/bones/json.py
  core/bones/key.py
  core/bones/numeric.py
  core/bones/randomslice.py
  core/bones/raw.py
  core/bones/record.py
  core/bones/relational.py
  core/bones/select.py
  core/bones/sortindex.py
  core/bones/spatial.py
  core/bones/string.py
  core/bones/text.py
  core/bones/user.py
Labels: Priority: Medium, refactoring

#733 refactor: Improving `DateBone.singleValueFromClient()`
  core/bones/date.py
Labels: refactoring

#797 Update test-suite Pipfile and add tests for `DateBone`
  tests/Pipfile
  tests/Pipfile.lock
  tests/bones/test_date_bone.py
Labels: feature, dependencies, Priority: Low, Tests

#798 Make recipients for `sendEMailToAdmins` configurable
  core/config.py
  core/email.py
Labels: feature, Priority: Medium

#789 fix: guessTimeZone() fails with Python 3.11
  core/bones/date.py
Labels: bug
