Repository viur-framework/viur-core, pull requests merged in 2023-04, with the labels that each got.

#683 feat: Allow `Enum` for `SelectBone`-values and implement `User`s status as `Enum`
  core/bones/select.py
  core/modules/user.py
Labels: feature, Priority: Medium

#703 fix: `SkelList.get_orders` must be in the `__slots__`
  core/skeleton.py
Labels: bug, Priority: High

#667 feat: Implement naive mode in `DateBone`
  core/bones/date.py
Labels: feature, Priority: Medium

#705 fix: Run render_structure recursively on "using" and "relskel"
  core/render/json/default.py
  core/skeleton.py
Labels: bug, hotfix, Priority: High

#708 fix: bump viur-datastore to 1.3.9
  requirements.txt
Labels: dependencies

#710 security: Ensure active status in authenticateUser
  core/modules/user.py
Labels: security, Priority: Critical

#706 fix: Improvements and clarifications on version string
  CHANGELOG.md
  core/config.py
  core/render/vi/__init__.py
  core/version.py
Labels: bug, hotfix, Priority: High

#692 chore: Conventional commits and clarifications
  CONTRIBUTING.md
Labels: documentation, discussion

#702 fix: `CredentialBone` without escaping
  core/bones/credential.py
Labels: bug, Priority: Medium

#721 doc: Set language in readthedocs config and add jQuery
  docs/conf.py
  docs/rtdtemplate/layout.html
Labels: bug, documentation, dependencies, Priority: Low

#720 fix: Hashable `user.Status`, improved "select"
  core/render/html/default.py
Labels: bug, hotfix, main

#726 fix: comparision in `SelectBone.singleValueFromClient`
  core/bones/select.py
Labels: bug, hotfix, Priority: High

#719 fix: SelectBone `defaultValue` type annotation
  core/bones/select.py
Labels: bug, Priority: Low, main

#728 doc: Watch the normal python code path in the doc build watcher too
  docs/Makefile
Labels: documentation, feature, Priority: Low

#729 doc: Add more selectors to theme.css to list styling from latest rdt theme
  docs/rtdtemplate/static/css/theme.css
  docs/rtdtemplate/static/css/theme.min.css
Labels: bug, documentation

#723 doc: Documentation for entire `bones`-module
  Pipfile.lock
  core/bones/base.py
  core/bones/boolean.py
  core/bones/captcha.py
  core/bones/color.py
  core/bones/credential.py
  core/bones/date.py
  core/bones/email.py
  core/bones/file.py
  core/bones/key.py
  core/bones/numeric.py
  core/bones/password.py
  core/bones/randomslice.py
  core/bones/raw.py
  core/bones/record.py
  core/bones/relational.py
  core/bones/select.py
  core/bones/selectcountry.py
  core/bones/sortindex.py
  core/bones/spatial.py
  core/bones/string.py
  core/bones/text.py
  core/bones/treeleaf.py
  core/bones/treenode.py
  core/bones/user.py
  docs/conf.py
Labels: documentation
