Repository viur-framework/viur-core, pull requests merged in 2023-01, with the labels that each got.

#603 Bump viur-datastore from 1.3.5 to 1.3.6
  requirements.txt
Labels: dependencies, main

#596 Fix stacklevel parameter for more precise deprecation messages
  core/bones/relational.py
  core/config.py
  core/tasks.py
  core/utils.py
Labels: refactoring, main

#601 Improving MetaBaseSkel.fill_bonemap_recursive
  core/skeleton.py
Labels: refactoring

#600 added back kindName for userSkel
  core/modules/user.py
Labels: hotfix, Priority: High

#588 Bump certifi from 2021.10.8 to 2022.12.7
  docs/Pipfile.lock
  requirements.txt
  tests/Pipfile.lock
Labels: dependencies, main

#592 Provide colorized local debug
  core/logging.py
Labels: feature, refactoring

#582 Move projectBasePath and coreBasePath
  core/config.py
  core/modules/user.py
  core/render/__init__.py
  core/render/html/default.py
  core/request.py
  core/skeleton.py
  core/utils.py
Labels: refactoring

#607 Refactoring render.vi.getStructure
  core/render/vi/__init__.py
Labels: hotfix, refactoring, main

#608 Provide defaultvalue in bone structure
  core/render/json/default.py
Labels: feature, hotfix, main

#609 Fix growing instance's Request header due continous change of global CSP rules
  core/securityheaders.py
Labels: hotfix, Priority: High, main

#610 Use editSkel() in Tree edit/delete
  core/prototypes/tree.py
Labels: hotfix, main

#558 Add `JsonBone`
  core/bones/__init__.py
  core/bones/json.py
Labels: feature

#624 Fix/viur cache
  core/cache.py
Labels: hotfix, Priority: High, main

#625 Reset renderPreparation in renderEmail
  core/render/html/default.py
  core/skeleton.py
Labels: hotfix, Priority: High, main

#621 Make MetaBaseSkel.generate_bonemap available
  core/skeleton.py
Labels: feature, refactoring

#620 Improvements for User module (substitutes #615)
  core/modules/user.py
  core/session.py
Labels: refactoring

#627 Bump viur-datastore from 1.3.6 to 1.3.7
  CHANGELOG.md
  core/version.py
  requirements.txt
Labels: dependencies, main

#628 Fix: Copy TextBone `_defaultTags` in `ModuleConfSkel`
  core/modules/moduleconf.py
Labels: hotfix, Priority: High, main

#614 Add Json Error Messages
  core/request.py
Labels: feature, Priority: Medium

#617 Implement a refresh method in the `NumericBone`
  core/bones/numeric.py
  tests/bones/test_numeric_bone.py
Labels: feature, Priority: Medium

#544 Session clean-up
  core/__init__.py
  core/config.py
  core/securityheaders.py
  core/session.py
Labels: refactoring

#611 Substitute `BaseApplication` by `Module` and `SkelModule` prototypes
  core/__init__.py
  core/config.py
  core/module.py
  core/modules/file.py
  core/modules/formmailer.py
  core/modules/moduleconf.py
  core/modules/user.py
  core/prototypes/__init__.py
  core/prototypes/list.py
  core/prototypes/singleton.py
  core/prototypes/skelmodule.py
  core/prototypes/tree.py
  core/render/__init__.py
  core/render/admin/__init__.py
  core/render/vi/__init__.py
  core/render/xml/__init__.py
Labels: feature, refactoring
