Repository viur-framework/viur-core, pull requests merged in 2023-08, with the labels that each got.

#805 chore: Update viur-datastore to 1.3.10
  requirements.txt
Labels: dependencies, Priority: High, main

#807 Fix docs configuration after #804
  docs/Makefile
  docs/Pipfile.lock
  docs/conf.py
Labels: bug, documentation, Priority: High

#810 fix: Add 'session_bound=False' for the skey
  src/viur/core/modules/user.py
Labels: hotfix, Priority: Medium

#814 chore: Update viur-datastore to 1.3.11
  requirements.txt
Labels: dependencies, Priority: High, main

#808 feat: Implement a `PeriodicTask` to check the remaining SIB email quota
  src/viur/core/email.py
Labels: feature, Priority: Medium

#809 feat: Implement natural sorting in `StringBone`
  src/viur/core/bones/string.py
Labels: feature, Priority: Medium

#802 refactor: User-module `TimeBasedOTP`
  Pipfile
  Pipfile.lock
  requirements.txt
  src/viur/core/modules/user.py
Labels: feature, Priority: High, refactoring, breaking-changes

#812 feat: Add bones parameter for renderEditForm
  src/viur/core/render/html/env/viur.py
Labels: feature, Priority: Medium

#712 feat: custom actions for user maintenance and debug triggers
  src/viur/core/modules/user.py
Labels: feature

#818 fix: `Tree.getRootNode` failed when parentrepo was None
  core/prototypes/tree.py
Labels: hotfix, main

#819 fix: `renderEditForm` failed when `ignore` or `bone` was None
  src/viur/core/render/html/env/viur.py
Labels: bug

#823 fix: Set test_threshold to 4 and add test_threshold to structure
  src/viur/core/bones/password.py
Labels: security, Priority: Medium
