Repository viur-framework/viur-core, pull requests merged in 2023-03, with the labels that each got.

#644 DateBone: Refactored test if to use guessTimeZone into guessTimeZone itself
  core/bones/date.py
Labels: Priority: Medium, refactoring

#654 Improve Cloud Tasks creation in `CallDeferred` and `QueryIter`
  core/tasks.py
Labels: bug, feature, Priority: Medium

#656 Refactoring `securitykey` module
  core/securitykey.py
Labels: refactoring

#665 Fallback to `SkelModule` as replacement for `BasicApplication`
  core/prototypes/__init__.py
Labels: refactoring

#672 Add structure for NumericBone
  core/bones/numeric.py
Labels: hotfix, Priority: High

#670 Fix spelling of "readonly" in `renderEditForm`
  core/render/html/env/viur.py
Labels: bug, Priority: High

#619 feat: Improve `PasswordBone` parametrization
  core/bones/password.py
  core/languages/de.py
  core/modules/user.py
Labels: feature, Priority: Medium, refactoring

#681 Capitalize classes to be PEP8 compliant
  core/modules/file.py
  core/modules/page.py
  core/modules/user.py
Labels: Priority: Low, refactoring

#664 Implement `script` system-module for Scriptor tree
  core/__init__.py
  core/config.py
  core/modules/script.py
Labels: feature

#657 feat: Support JSON Schema validation for `JsonBone`
  core/bones/json.py
  requirements.txt
  tests/requirements.txt
Labels: feature

#688 refactor: rename `Skeleton.toDB()`s `clearUpdateTag` into `update_relations`
  core/bones/file.py
  core/modules/user.py
  core/skeleton.py
Labels: refactoring

#690 fix: Return JSON-encoded response for internal server errors too
  core/request.py
Labels: bug, Priority: Medium

#677 feat: UserSkel improvements (`firstname`, `lastname`, `sync`) and Google Auth user information synchronization
  core/modules/user.py
Labels: feature, Priority: Medium

#693 feat: Add `manage` access right
  core/prototypes/list.py
  core/prototypes/singleton.py
  core/prototypes/tree.py
Labels: feature, Priority: Low

#694 refactor: Replace `doClear*` by `DeleteEntitiesIter`
  core/securitykey.py
  core/session.py
Labels: Priority: Low, refactoring

#696 fix: ignore downloadUrls without signature
  core/bones/text.py
Labels: bug

#697 fix: continue thumbnailing when image is broken
  core/modules/file.py
Labels: bug

#680 refactor: Re-implement password encoding using Python's `hashlib` and `secrets` module
  core/bones/password.py
  core/modules/user.py
  core/utils.py
Labels: feature, security, Priority: High, refactoring

#699 fix: Keep filename synchronous in both skeleton and blob
  core/modules/file.py
Labels: bug, Priority: Medium
