Repository viur-framework/viur-core, pull requests merged in 2023-12, with the labels that each got.

#941 fix: Invalid `maxLength` check in `StringBone`
  src/viur/core/bones/string.py
Labels: hotfix, Priority: High

#957 fix: `defaultValue` type hint in `SelectBone`
  src/viur/core/bones/select.py
Labels: invalid, Priority: Low, python

#962 fix: kwargs checks must be underline (`_`) prefixed as well
  src/viur/core/tasks.py
Labels: bug, Priority: Low, python

#953 refactor: Replace the `replace` function with `translate`
  src/viur/core/bones/text.py
  src/viur/core/skeleton.py
  src/viur/core/utils.py
Labels: Priority: Low, refactoring

#966 feat: Add stacklevels to `warning.warn` calls
  src/viur/core/bones/__init__.py
  src/viur/core/config.py
Labels: feature, Priority: Low

#964 fix: `exclude_from_indexes` has to be a set
  src/viur/core/cache.py
  src/viur/core/email.py
  src/viur/core/session.py
  src/viur/core/skeleton.py
Labels: invalid, Priority: Medium, python

#959 feat: Add logging with the name of the bone where the serialization failed
  src/viur/core/skeleton.py
Labels: feature, Priority: Low, python

#971 fix: `@retry_n_times` does not work on local server during warmup
  src/viur/core/tasks.py
Labels: hotfix, Priority: High

#970 fix: Add `try`/`except` around task emulation call
  src/viur/core/request.py
Labels: hotfix, Priority: High

#945 refactor: static skey marker
  src/viur/core/modules/user.py
  src/viur/core/securitykey.py
Labels: Priority: Low, refactoring

#979 fix: Admin-tool specific settings
  src/viur/core/render/vi/__init__.py
Labels: hotfix, Priority: High

#981 fix: Set correct stacklevel to deprecation warning on `utils.escapeString`
  src/viur/core/bones/string.py
Labels: hotfix, Priority: Medium

#980 fix: Start explicit with `main_app` in `findBoundTask()`
  src/viur/core/tasks.py
Labels: hotfix, Priority: High

#961 fix: disable cookie's `SameSite` and `Secure` for local server
  src/viur/core/session.py
Labels: hotfix, security, Priority: Critical, main

#989 fix: wrong conf var access
  src/viur/core/email.py
Labels: hotfix, Priority: High

#975 feat: Add `File.read()` method
  src/viur/core/modules/file.py
Labels: feature, Priority: Medium

#990 feat: Improved and slightly refactored `PasswordBone`
  src/viur/core/bones/password.py
  src/viur/core/modules/user.py
Labels: refactoring

#987 feat: Provide `UserPassword.on_login()` hook
  src/viur/core/modules/user.py
Labels: feature, Priority: High, main

#967 Implement `InstancedModule`
  src/viur/core/__init__.py
  src/viur/core/prototypes/instanced_module.py
Labels: feature, Priority: High

#992 feat: Refactoring and renamed `utils`, adding `utils.string.unescape`
  src/viur/core/__init__.py
  src/viur/core/bones/boolean.py
  src/viur/core/bones/password.py
  src/viur/core/bones/string.py
  src/viur/core/module.py
  src/viur/core/modules/file.py
  src/viur/core/modules/user.py
  src/viur/core/prototypes/list.py
  src/viur/core/prototypes/singleton.py
  src/viur/core/prototypes/tree.py
  src/viur/core/render/html/env/viur.py
  src/viur/core/request.py
  src/viur/core/securitykey.py
  src/viur/core/session.py
  src/viur/core/skeleton.py
  src/viur/core/tasks.py
  src/viur/core/utils/__init__.py
  src/viur/core/utils/parse.py
  src/viur/core/utils/string.py
  tests/test_utils.py
Labels: feature, refactoring

#998 fix: Adding linter settings for flake8 as well
  tox.ini
Labels: hotfix, viur-meeting, pep8

#1002 fix: Undocumented and uninitialized `conf["viur.user.google.gsuiteDomains"]`
  src/viur/core/config.py
  src/viur/core/modules/user.py
Labels: hotfix, main

#1001 feat: Implement `@property` support in `Skeleton`s
  src/viur/core/skeleton.py
Labels: feature, Priority: High

#1003 fix: Broken use of tasks emulator in combination with the app_server
  src/viur/core/tasks.py
Labels: hotfix, Priority: High

#1006 fix: handling alpha channel within thumbnail generation if icc profile is present
  src/viur/core/modules/file.py
Labels: bug, hotfix, Priority: High

#1004 fix: support for tasks emulator
  src/viur/core/tasks.py
Labels: hotfix, Priority: Medium, refactoring
