Repository viur-framework/viur-core, pull requests merged in 2023-02, with the labels that each got.

#640 Fix module import in formmailer, introduced in #611
  core/modules/formmailer.py
Labels: bug, Priority: High

#638 Add `conf["viur.dev_server_cloud_logging"]`
  core/config.py
  core/request.py
Labels: feature, Priority: Low

#645 Avoid that session is written twice when validating an skey
  core/session.py
Labels: hotfix, Priority: Medium

#636 Add JsonBone for the user to store config information.
  core/modules/user.py
Labels: feature, Priority: Medium

#637 Move structure dict rendering from the renders into the bones
  core/bones/base.py
  core/bones/date.py
  core/bones/file.py
  core/bones/record.py
  core/bones/relational.py
  core/bones/select.py
  core/bones/spatial.py
  core/bones/string.py
  core/bones/text.py
  core/config.py
  core/render/html/default.py
  core/render/html/env/viur.py
  core/render/json/default.py
  core/render/vi/__init__.py
  core/render/xml/default.py
  core/skeleton.py
Labels: feature, Priority: Medium, refactoring

#635 `current`-module to handle ContextVars, new `current.user` ContextVar
  core/__init__.py
  core/bones/captcha.py
  core/bones/date.py
  core/bones/string.py
  core/bones/user.py
  core/cache.py
  core/current.py
  core/i18n.py
  core/logging.py
  core/modules/file.py
  core/modules/user.py
  core/prototypes/list.py
  core/prototypes/singleton.py
  core/prototypes/tree.py
  core/ratelimit.py
  core/render/html/default.py
  core/render/html/env/session.py
  core/render/html/env/viur.py
  core/render/json/default.py
  core/render/vi/__init__.py
  core/request.py
  core/securityheaders.py
  core/securitykey.py
  core/session.py
  core/skeleton.py
  core/tasks.py
  core/utils.py
  docs/doc_tutorial/advanced/15_training_tasks.rst
Labels: feature, Priority: Medium, refactoring, pep8
