Repository viur-framework/viur-core, pull requests merged in 2023-10, with the labels that each got.

#899 chore: Update dependencies to latest version
  Pipfile
  Pipfile.lock
  docs/Pipfile.lock
  src/viur/core/requirements.txt
  tests/Pipfile.lock
Labels: dependencies

#900 fix: Built a standardized way for the return of errors in 2Factor
  src/viur/core/modules/user.py
Labels: hotfix, main

#911 fix: Add `google-api-core[grpc]` and `googleapis-common-protos[grpc]`
  Pipfile
  Pipfile.lock
  setup.py
  src/viur/core/requirements.txt
Labels: bug, dependencies, main

#918 chore: Downgrade urllib3 to `1.26.17`
  Pipfile
  Pipfile.lock
  src/viur/core/requirements.txt
Labels: hotfix, main

#917 cicd: Add python 3.11 to matrix in test workflow
  .github/workflows/python-test.yaml
Labels: Priority: Low, ci/cd, main

#914 docs: Improve and correct session docs
  docs/doc_tutorial/advanced/05_training_config.rst
  docs/doc_tutorial/advanced/10_training_session.rst
Labels: documentation, main

#912 docs: Fix SEO training after renaming in #800
  docs/doc_tutorial/advanced/training_seo.rst
Labels: documentation

#913 docs: remove old configs, fix RST-Syntax and adjustments for server->core
  docs/doc_tutorial/advanced/05_training_config.rst
  src/viur/core/config.py
Labels: documentation, main

#916 docs: Improve basics and getting started tutorials
  docs/doc_guide/15_implementation_randomSliceBone.rst
  docs/doc_guide/20_implementation_spatialBone.rst
  docs/doc_start/05_intro.rst
  docs/doc_start/10_start.rst
  docs/doc_start/15_basics.rst
  docs/doc_start/20_troubleshooting.rst
  docs/doc_start/30_myfirstproject.rst
  docs/doc_start/index.rst
  docs/doc_tutorial/advanced/15_training_tasks.rst
  docs/doc_tutorial/basic/05_training_modulemng.rst
  docs/doc_tutorial/basic/10_training_datamng.rst
Labels: documentation

#915 docs: Improve and correct tasks docs tutorial
  docs/doc_tutorial/advanced/15_training_tasks.rst
Labels: documentation

#910 feat: `utils.is_prefix`-function
  src/viur/core/utils.py
Labels: feature, Priority: Low

#922 fix:Add allow_empty=True for tasks/execute
  src/viur/core/tasks.py
Labels: hotfix, Priority: High, main

#833 Implement the Config as (real) Object with attributes
  src/viur/core/__init__.py
  src/viur/core/bones/base.py
  src/viur/core/bones/boolean.py
  src/viur/core/bones/captcha.py
  src/viur/core/bones/date.py
  src/viur/core/bones/file.py
  src/viur/core/bones/password.py
  src/viur/core/cache.py
  src/viur/core/config.py
  src/viur/core/db.py
  src/viur/core/email.py
  src/viur/core/i18n.py
  src/viur/core/logging.py
  src/viur/core/module.py
  src/viur/core/modules/file.py
  src/viur/core/modules/moduleconf.py
  src/viur/core/modules/script.py
  src/viur/core/modules/user.py
  src/viur/core/render/html/default.py
  src/viur/core/render/html/env/viur.py
  src/viur/core/render/json/default.py
  src/viur/core/render/vi/__init__.py
  src/viur/core/render/xml/__init__.py
  src/viur/core/request.py
  src/viur/core/secret.py
  src/viur/core/securityheaders.py
  src/viur/core/securitykey.py
  src/viur/core/session.py
  src/viur/core/skeleton.py
  src/viur/core/tasks.py
  src/viur/core/utils.py
  tests/test_config.py
Labels: feature, refactoring, viur-meeting

#901 feat: Add user admin login context
  src/viur/core/render/vi/user.py
Labels: feature, Priority: Medium, viur-meeting, main

#867 feat: Add new error template with a nonce and custom image
  src/viur/core/config.py
  src/viur/core/languages/de.py
  src/viur/core/request.py
  src/viur/core/template/error.html
Labels: feature, Priority: Medium

#925 feat: Provide computed `name`-bone for `Skeleton`
  src/viur/core/skeleton.py
Labels: feature

#927 fix: Refactor usage of `SeoKeyBone` in `Skeleton`
  src/viur/core/skeleton.py
Labels: refactoring

#926 fix: Clean-up Skeletons `key` default bone
  src/viur/core/skeleton.py
Labels: refactoring
