Repository viur-framework/viur-core, pull requests merged in 2023-06, with the labels that each got.

#759 fix: ensure the correct default defaultValue of a multiple/multi-lang `BooleanBone`
  core/bones/boolean.py
Labels: bug, Priority: Medium

#743 fix: `File.getUploadURL` with HttpExceptions
  core/errors.py
  core/modules/file.py
Labels: bug, refactoring

#739 feat: Delete old pending `FileSkeletons`
  core/modules/file.py
  core/tasks.py
Labels: feature, Priority: Low

#763 fix: Missing german translation for "password too short" message
  core/languages/de.py
Labels: bug

#773 chore: Reject pointless `BooleanBone(multiple=True)`
  core/bones/boolean.py
  core/bones/credential.py
Labels: main

#774 perf: Avoid structure rendering in JSON render list
  core/config.py
  core/render/json/default.py
Labels: refactoring, performance

#767 chore: Support for Python 3.11
  CONTRIBUTING.md
  Pipfile
  Pipfile.lock
  core/bones/record.py
  core/config.py
  core/skeleton.py
  requirements.txt
Labels: security, Priority: High, refactoring, performance

#764 feat: Rewrite of session-based securitykeys
  core/modules/file.py
  core/modules/formmailer.py
  core/modules/user.py
  core/prototypes/list.py
  core/prototypes/singleton.py
  core/prototypes/tree.py
  core/render/json/__init__.py
  core/securitykey.py
  core/session.py
  core/tasks.py
Labels: feature, Priority: High, refactoring

#736 feat: Extend User module to built-in role system
  core/config.py
  core/languages/de.py
  core/module.py
  core/modules/file.py
  core/modules/script.py
  core/modules/user.py
  core/prototypes/skelmodule.py
Labels: feature
