Repository viur-framework/viur-core, pull requests merged in 2023-05, with the labels that each got.

#738 fix:readd StringBone type
  core/bones/string.py
Labels: bug, Priority: High

#740 fix: Remove leading `Subject: ` from task notify emails
  core/skeleton.py
Labels: Priority: Low

#737 fix: Rename `Skeleton.__undefined` into `Skeleton._undefined`
  core/skeleton.py
Labels: bug, Priority: Critical

#745 Remove an `if`, otherwise the `else` case is missing and we have a path with `res = None`
  core/request.py
Labels: bug

#744 feat: Set `cls` to `CustomJsonEncoder` in Jinja's `json.dumps_kwargs`
  core/render/html/default.py
Labels: feature, Priority: Medium

#747 fix: Add path_list to the __init__ of BrowseHandler
  core/request.py
Labels: hotfix, Priority: High, main

#750 fix: `CredentialBone` without escaping (#702) - readded to main
  core/bones/credential.py
Labels: bug, Priority: High, main

#751 feat/fix: Allow `duration` argument for skey
  core/render/json/__init__.py
  core/render/vi/__init__.py
  core/request.py
Labels: bug, feature, Priority: High, main

#749 fix: `DateBone.fromClient()` should regard tzinfo
  core/bones/date.py
Labels: bug, hotfix, Priority: High, main

#748 fix: Fixes TypeError when password is unset
  core/modules/user.py
Labels: bug, hotfix, Priority: High, main
