Repository viur-framework/viur-core, pull requests merged in 2023-09, with the labels that each got.

#682 refactor: Refactor password recovery process in stock `User`-module
  Pipfile
  requirements.txt
  src/viur/core/config.py
  src/viur/core/modules/user.py
  src/viur/core/securitykey.py
Labels: feature, Priority: Medium

#655 feat: Implement `retry_n_times` decorator
  src/viur/core/tasks.py
Labels: feature, Priority: Medium

#800 feat: Implement a new `Module`/`Method` concept with new decorators
  src/viur/core/__init__.py
  src/viur/core/config.py
  src/viur/core/decorators.py
  src/viur/core/module.py
  src/viur/core/modules/file.py
  src/viur/core/modules/formmailer.py
  src/viur/core/modules/site.py
  src/viur/core/modules/user.py
  src/viur/core/prototypes/list.py
  src/viur/core/prototypes/singleton.py
  src/viur/core/prototypes/tree.py
  src/viur/core/render/html/env/viur.py
  src/viur/core/render/json/__init__.py
  src/viur/core/render/vi/__init__.py
  src/viur/core/render/xml/__init__.py
  src/viur/core/request.py
  src/viur/core/securitykey.py
  src/viur/core/tasks.py
  src/viur/core/utils.py
Labels: feature, Priority: High, refactoring, performance

#815 feat: Add `secret` module to access values from GC secret manager
  Pipfile
  Pipfile.lock
  requirements.txt
  src/viur/core/secret.py
Labels: feature, dependencies

#837 feat: Extend `Method` to examine function signature and parse type annotations
  src/viur/core/decorators.py
  src/viur/core/module.py
  src/viur/core/prototypes/list.py
  src/viur/core/prototypes/tree.py
  src/viur/core/request.py
Labels: feature, Priority: High, refactoring

#838 feat: Implement `utils.parse_bool`
  src/viur/core/bones/boolean.py
  src/viur/core/modules/user.py
  src/viur/core/prototypes/list.py
  src/viur/core/prototypes/singleton.py
  src/viur/core/prototypes/tree.py
  src/viur/core/request.py
  src/viur/core/tasks.py
  src/viur/core/utils.py
Labels: feature, Priority: Medium

#843 fix: Add default value for `token` in `GoogleAccount.login()`, otherwise the process cannot be started
  src/viur/core/modules/user.py
Labels: bug, Priority: High

#578 feat: Second factor OTP login using Authenticator App
  Pipfile
  requirements.txt
  src/viur/core/config.py
  src/viur/core/modules/user.py
  src/viur/core/render/html/env/viur.py
  src/viur/core/render/html/user.py
  src/viur/core/render/json/user.py
Labels: feature, Priority: Low

#844 fix: import qrcode's element with an alias
  src/viur/core/render/html/env/viur.py
Labels: bug, Priority: High

#847 fix: Replace call to `utils.getCurrentUser()`
  src/viur/core/modules/script.py
Labels: refactoring

#846 fix some mixed up and blurred methods and concepts.
  src/viur/core/modules/user.py
  src/viur/core/render/html/user.py
Labels: bug, Priority: High

#849 fix: _route list parsing for multiple bones
  src/viur/core/request.py
Labels: bug, Priority: High

#848 fix: Clean-up user/view and user/edit with "self"
  src/viur/core/module.py
  src/viur/core/modules/user.py
Labels: bug, feature

#845 fix: template name should not be static.
  src/viur/core/modules/user.py
  src/viur/core/render/html/user.py
Labels: bug, Priority: High

#850 fix: Replace forward_argument by forward_payload in `/user/verify`
  src/viur/core/module.py
  src/viur/core/modules/user.py
Labels: bug, Priority: High

#857 fix `user/verify/` return skel in transaction
  src/viur/core/modules/user.py
Labels: bug, Priority: High

#865 fix: Remove replace of `.` to `_`
  src/viur/core/request.py
Labels: bug, Priority: High

#869 fix: Move warning-email "Debug mode enabled"
  src/viur/core/__init__.py
Labels: bug

#870 fix: Remove the `style` which is reserved for template completely from the request kwargs
  src/viur/core/render/html/default.py
  src/viur/core/render/html/env/viur.py
  src/viur/core/request.py
Labels: bug, Priority: High

#859 feat: Implement `__all__` in root's `__init__` and `decorators` to support easier imports
  src/viur/core/__init__.py
  src/viur/core/decorators.py
Labels: feature

#875 fix(docs): Add and lock all docs dependencies
  docs/Pipfile
  docs/Pipfile.lock
  docs/requirements.txt
Labels: bug, documentation, dependencies, Priority: High, ci/cd
