Repository viur-framework/viur-core, pull requests merged in 2023-11, with the labels that each got.

#928 fix: refactor `pathlist` to `path_list`
  src/viur/core/cache.py
Labels: bug, hotfix, Priority: Critical

#929 fix: invalid `conf` refactoring
  src/viur/core/cache.py
  src/viur/core/render/html/env/viur.py
Labels: bug, Priority: High

#930 fix: Raise an `AttributeError` in case of `KeyError` in `SkeletonInstance.boneMap`
  src/viur/core/skeleton.py
Labels: bug, Priority: Critical

#931 fix: Always set `Secure` mode for session cookie
  src/viur/core/session.py
Labels: bug, hotfix, main

#936 fix: `access` in method description must not be a generator object
  src/viur/core/module.py
Labels: bug, Priority: Critical

#937 feat: use `CustomJsonEncoder` class in `json.dumps` call
  src/viur/core/render/json/default.py
  src/viur/core/render/json/user.py
  src/viur/core/render/vi/__init__.py
Labels: feature, Priority: High

#939 fix: User-module default customAction triggers require skey
  src/viur/core/modules/user.py
Labels: hotfix, main

#938 fix: Update dependencies, urllib3 CVE-2023-45803
  Pipfile
  Pipfile.lock
  src/viur/core/requirements.txt
Labels: security, dependencies, main

#940 feat: Add `min_length` to `StringBone`
  src/viur/core/bones/string.py
Labels: feature, Priority: Low

#942 refactor: Rename `StringBone`'s `maxLength` into `max_length`
  src/viur/core/bones/credential.py
  src/viur/core/bones/string.py
  src/viur/core/bones/text.py
  src/viur/core/utils.py
  tests/test_utils.py
Labels: Priority: Low, refactoring
