Repository viur-framework/viur-core, pull requests merged in 2024-09, with the labels that each got.

#1250 refactor: Send emails from `EmailTransport` instances instead of class
  docs/doc_tutorial/advanced/05_training_config.rst
  pyproject.toml
  src/viur/core/config.py
  src/viur/core/email.py
  src/viur/core/modules/formmailer.py
  src/viur/core/modules/user.py
  src/viur/core/skeleton.py
  src/viur/core/tasks.py
Labels: Priority: Medium, refactoring, breaking-changes

#1253 doc+fix: Added module docstrings, removed render defaults
  src/viur/core/modules/file.py
  src/viur/core/modules/formmailer.py
  src/viur/core/modules/moduleconf.py
  src/viur/core/modules/page.py
  src/viur/core/modules/script.py
  src/viur/core/modules/site.py
  src/viur/core/modules/translation.py
  src/viur/core/modules/user.py
Labels: bug(fix), security, Priority: High

#1258 fix: Delete bones set to `None` from a Skeleton
  src/viur/core/skeleton.py
Labels: bug(fix), Priority: High, viur-meeting, main

#1257 fix: @access-decorator
  src/viur/core/module.py
Labels: bug(fix), security, Priority: High, main

#1198 refactor: `DatabaseAdapter` with simplified triggers
  src/viur/core/skeleton.py
  src/viur/core/utils/__init__.py
Labels: feature, Priority: High, refactoring, breaking-changes

#1261 feat: `type_postfix` on `BaseBone` and `select.access` in `UserSkel`
  src/viur/core/bones/base.py
  src/viur/core/modules/user.py
Labels: feature, viur-meeting, main

#1205 feat: Add `PhoneBone`
  src/viur/core/bones/__init__.py
  src/viur/core/bones/phone.py
Labels: feature, usability

#1251 feat: Implement `EmailTransportSmtp`
  src/viur/core/email.py
Labels: feature, Priority: Medium

#1263 fix: Cast category to str() for ascii check
  src/viur/core/render/html/env/viur.py
Labels: Priority: High, main

#1241 feat: `FileBone(public=True)` for public files
  src/viur/core/bones/file.py
  src/viur/core/modules/file.py
  src/viur/core/render/html/env/viur.py
Labels: feature, Priority: High, viur-meeting

#1262 feat: Make SkeletonInstance json serializable
  src/viur/core/bones/json.py
  src/viur/core/render/json/default.py
  src/viur/core/utils/json.py
Labels: feature, Priority: Medium

#1269 fix: `RelationalBone.singleValueFromClient` str-cast
  src/viur/core/bones/relational.py
Labels: bug(fix), usability

#1268 chore: Adding file deprecations
  src/viur/core/modules/file.py
Labels: refactoring, usability

#1275 fix: Rename `type_postfix` on `BaseBone` into `type_suffix`
  CHANGELOG.md
  src/viur/core/bones/base.py
  src/viur/core/modules/user.py
  src/viur/core/version.py
Labels: Priority: High, main

#1204 fix: Clean-up `KeyBone` and added unserialization
  src/viur/core/bones/key.py
Labels: Priority: Medium, refactoring, performance, usability

#1266 fix: handle gracefully downloadurls and srcsets with optional languages overwrite for files
  src/viur/core/modules/file.py
  src/viur/core/render/html/env/viur.py
Labels: bug(fix)
