Repository viur-framework/viur-core, pull requests merged in 2024-02, with the labels that each got.

#1054 fix: f-string in `RelationalBone` introduced in #950
  src/viur/core/bones/relational.py
Labels: bug(fix), Priority: Critical

#946 refactor value for `tasks_custom_environment_handler` to new abstract class `CustomEnvironmentHandler`
  src/viur/core/config.py
  src/viur/core/tasks.py
Labels: Priority: Low, refactoring

#983 feat: `UserAuthentication`s with skeleton patch capability
  src/viur/core/modules/user.py
Labels: feature

#1060 fix: patch_user_skel (fix for #983)
  src/viur/core/modules/user.py
Labels: bug(fix), Priority: High

#1055 feat: Improve `UserBone` to additional defaults
  src/viur/core/bones/user.py
Labels: feature, refactoring

#1058 refactor: `RelationalBone`s `refKeys` and `parentKeys` as set
  src/viur/core/bones/file.py
  src/viur/core/bones/relational.py
Labels: refactoring

#1066 fix: correctly set `refKeys` to get merged in
  src/viur/core/bones/file.py
Labels: bug(fix), Priority: High

#1065 fix: Use `__getattribute__` instead of `__getattr__` for super call in utils
  src/viur/core/utils/__init__.py
Labels: bug(fix), Priority: Medium

#1067 fix: `current.user` unset in deferred task calls
  CHANGELOG.md
  src/viur/core/modules/user.py
  src/viur/core/tasks.py
  src/viur/core/version.py
Labels: bug(fix), main

#1016 refactor: `tasks` module
  src/viur/core/tasks.py
Labels: Priority: Medium, refactoring

#1069 fix: new icon naming scheme in modules
  src/viur/core/config.py
  src/viur/core/modules/file.py
  src/viur/core/modules/page.py
  src/viur/core/modules/user.py
Labels: bug(fix), Priority: High

#1037 fix: Remove default `P.html = True` from prototypes
  src/viur/core/prototypes/list.py
  src/viur/core/prototypes/singleton.py
Labels: bug(fix), security, Priority: High

#1073 fix: Several improvements on `ModuleConf`
  CHANGELOG.md
  src/viur/core/modules/moduleconf.py
  src/viur/core/version.py
Labels: bug(fix), Priority: High, refactoring, main

#1075 fix: Make ViUR runable again after the extremely security-relevant PR #1037
  src/viur/core/bones/text.py
  src/viur/core/email.py
  src/viur/core/modules/moduleconf.py
  src/viur/core/modules/user.py
  src/viur/core/request.py
  src/viur/core/session.py
  src/viur/core/tasks.py
Labels: bug(fix), Priority: Critical

#1074 fix: `read_all_modules` after #1073 and #1037 and merge 2a2b76ec16
  src/viur/core/modules/moduleconf.py
Labels: bug(fix), Priority: High

#1079 fix: Remove `self` from `create_src_set`
  src/viur/core/modules/file.py
Labels: Priority: High

#1078 feat: securitykey create duration allow timedelta
  src/viur/core/securitykey.py
Labels: Priority: Low

#1053 feat: Allow `None` in `skel setBoneValue`
  src/viur/core/skeleton.py
Labels: feature, Priority: Low

#1072 feat: `utils.json` module / improving `JsonBone`
  src/viur/core/bones/json.py
  src/viur/core/tasks.py
  src/viur/core/utils/__init__.py
  src/viur/core/utils/json.py
  tests/main.py
  tests/test_utils.py
Labels: feature, refactoring

#997 feat: `UserPrimaryAuthentication.next_or_finish` handler
  src/viur/core/modules/user.py
Labels: feature, refactoring
