Repository viur-framework/viur-core, pull requests merged in 2024-06, with the labels that each got.

#1103 feat: add `skel.update` and `skel.__ior__`
  src/viur/core/skeleton.py
Labels: Priority: Low

#1186 feat: Add `sorted` feature to `MultipleConstraints`
  src/viur/core/bones/base.py
Labels: feature, Priority: Low

#1184 fix: Keep HTML-entities in `HtmlSerializer`
  src/viur/core/bones/text.py
  tests/bones/test_text_bone.py
Labels: bug(fix), Priority: High

#1188 fix: `default_order` and `query.queries` can be a list
  src/viur/core/modules/moduleconf.py
  src/viur/core/prototypes/list.py
  src/viur/core/prototypes/tree.py
Labels: bug(fix), Priority: Critical, main

#1183 feat: Add charset `v_func` for `StringBone`
  src/viur/core/bones/string.py
Labels: feature, Priority: Low

#1177 fix: Add `google.cloud.logging_v2.handlers.transports.background_thread` to the `EXCLUDED_LOGGER_DEFAULTS`
  src/viur/core/logging.py
Labels: Priority: Medium, main

#1107 feat: store compute value on unserialize
  src/viur/core/bones/base.py
Labels: bug(fix), Priority: Medium, main

#1180 feat: Add checksums for files
  src/viur/core/modules/file.py
Labels: Priority: Low

#1190 feat: Implement abstract renderer
  src/viur/core/render/abstract.py
  src/viur/core/render/html/default.py
  src/viur/core/render/json/default.py
  src/viur/core/render/xml/default.py
Labels: feature, refactoring, python

#1195 fix: Remove `default_order` fallback from `List`
  src/viur/core/prototypes/list.py
Labels: Priority: High, main, requirement

#1196 fix: Changed `EmailTransportMailjet` mimetype detection to `puremagic`
  CHANGELOG.md
  Pipfile
  Pipfile.lock
  setup.cfg
  src/viur/core/config.py
  src/viur/core/email.py
  src/viur/core/requirements.txt
  src/viur/core/version.py
Labels: Priority: High, refactoring, main, requirement

#1197 feat: Backport `EmailTransportMailjet` to v3.5
  CHANGELOG.md
  Pipfile
  Pipfile.lock
  setup.cfg
  src/viur/core/email.py
  src/viur/core/requirements.txt
  src/viur/core/version.py
Labels: feature, Priority: High, requirement

#1199 fix: Improve interval format warning in `PeriodicTask`
  src/viur/core/tasks.py
Labels: Priority: Low, refactoring, usability
