Repository viur-framework/viur-core, pull requests merged in 2024-08, with the labels that each got.

#1225 fix: Add datetime import in email.py
  src/viur/core/email.py
Labels: bug(fix), Priority: High

#1231 refactor: Move datastore index retrieval to `SkelModule`
  src/viur/core/__init__.py
  src/viur/core/prototypes/skelmodule.py
Labels: bug(fix), refactoring

#1235 fix: `File`-module allows to upload into nonexisting node
  src/viur/core/modules/file.py
Labels: bug(fix), security, Priority: High, main

#1227 feat: Retrieve default `descr` from bone's name in its Skeleton
  src/viur/core/bones/base.py
  src/viur/core/i18n.py
Labels: feature

#1228 fix: `MultipleConstraints` as intended
  src/viur/core/bones/base.py
  src/viur/core/bones/record.py
  src/viur/core/bones/relational.py
Labels: bug(fix), refactoring, viur-meeting

#1233 feat: Extend `CONTRIBUTING.md` with Coding Conventions
  CONTRIBUTING.md
Labels: documentation, Priority: Low, viur-meeting

#1238 fix: null-key always written into `viur-relations`
  src/viur/core/bones/relational.py
Labels: bug(fix), Priority: High, main

#1239 refactor: Move datastore index retrieval to `SkelModule` (backport v3.6)
  src/viur/core/__init__.py
  src/viur/core/prototypes/skelmodule.py
Labels: bug(fix), Priority: High, refactoring, main

#1240 refactor: `__build_app` function clean-up and make all modules accessible
  src/viur/core/__init__.py
Labels: bug(fix), Priority: High, refactoring, main

#1237 fix: Inconsistency raises AssertionError
  src/viur/core/skeleton.py
Labels: bug(fix), Priority: Medium, main

#1244 fix: Re-Implement `RelationalConsistency.PreventDeletion` validation
  src/viur/core/bones/relational.py
  src/viur/core/skeleton.py
Labels: bug(fix), Priority: Critical, viur-meeting, main

#1245 fix: Improve `NumericBone.singleValueFromClient`
  src/viur/core/bones/numeric.py
  tests/bones/test_numeric_bone.py
Labels: bug(fix), Priority: Medium, viur-meeting, main

#1230 fix: Cleanly collect renders from Python module
  src/viur/core/__init__.py
Labels: bug(fix), refactoring

#1243 feat: Improve `CaptchaBone`
  src/viur/core/bones/captcha.py
  src/viur/core/config.py
Labels: feature, Priority: Medium

#1246 fix: `SpamBone` regression of descr-property
  src/viur/core/bones/spam.py
Labels: bug(fix), Priority: High

#1247 fix+doc: PeriodicTask
  src/viur/core/modules/file.py
  src/viur/core/tasks.py
Labels: documentation, refactoring

#1248 fix: `Skeleton.toDB()`s `is_add` determined wrong
  src/viur/core/skeleton.py
Labels: bug(fix), Priority: Critical, main

#1249 feat: Implement `EmailTransportSendgrid`
  src/viur/core/config.py
  src/viur/core/email.py
Labels: feature, Priority: Low
