Repository viur-framework/viur-core, pull requests merged in 2024-03, with the labels that each got.

#1091 chore: Update requirements to latest patchlevels
  Pipfile.lock
  src/viur/core/requirements.txt
Labels: dependencies

#1088 fix: `vi.canAccess` based on fnmatch config setting
  src/viur/core/config.py
  src/viur/core/render/vi/__init__.py
  src/viur/core/request.py
Labels: bug(fix), feature, Priority: High

#1094 refactor: Remove old code
  src/viur/core/skeleton.py
Labels: Priority: Low, refactoring

#1089 fix: Improving `utils` deprecation handling
  src/viur/core/utils/__init__.py
Labels: bug(fix), Priority: High, refactoring

#1086 feat: Implement `utils.parse.timedelta`
  src/viur/core/cache.py
  src/viur/core/securitykey.py
  src/viur/core/utils/parse.py
  tests/test_utils.py
Labels: feature, Priority: Low

#1022 feat: Support `*`-wildcard postfix in `refKeys` for `RelationalBones`
  src/viur/core/bones/relational.py
  src/viur/core/skeleton.py
Labels: feature, proposal, Priority: High

#988 feat: Allow `None` as defaultValue in BooleanBone
  src/viur/core/bones/boolean.py
Labels: feature, Priority: High

#1105 fix: file module typo `UnprocessableEntity`
  src/viur/core/modules/file.py
Labels: bug(fix), typo, Priority: High

#1102 fix: User roles: Automatic "view" right when "edit" or "delete" is provided
  CHANGELOG.md
  src/viur/core/modules/user.py
  src/viur/core/version.py
Labels: bug(fix), main

#1112 fix: Handle non-ASCII characters in username comparison
  CHANGELOG.md
  src/viur/core/modules/user.py
  src/viur/core/version.py
Labels: bug(fix), Priority: High

#1111 fix: Add `_prevent_compute` for computed Bones
  src/viur/core/bones/base.py
Labels: bug(fix), Priority: High

#1109 feat: `default_order` should support multiple orders as well
  src/viur/core/prototypes/list.py
  src/viur/core/prototypes/skelmodule.py
  src/viur/core/prototypes/tree.py
Labels: bug(fix), feature, Priority: High

#1118 feat: Provide `LoginSkel` on `UserPassword.login`
  src/viur/core/bones/password.py
  src/viur/core/modules/user.py
Labels: feature, Priority: High

#1120 fix: Add `is None`-check for bone values with languages
  src/viur/core/render/json/default.py
  src/viur/core/render/xml/default.py
Labels: bug(fix), Priority: High

#1122 fix: Broken access to methods in `File` class by refactoring
  src/viur/core/render/html/env/viur.py
Labels: bug(fix), Priority: Critical

#1124 fix: `TimeBasedOTP.start()` should use UserSkel
  src/viur/core/modules/user.py
Labels: bug(fix), Priority: High, main
