Repository viur-framework/viur-core, pull requests merged in 2024-01, with the labels that each got.

#994 fix: Provide "moduleGroups" in `/vi/config`
  src/viur/core/config.py
Labels: hotfix, Priority: High

#1014 fix: Some more fixes for #833
  src/viur/core/config.py
  src/viur/core/scripts/migrate_config.py
Labels: hotfix, Priority: High

#1021 fix: config regression after incorrect merge 537f0e2
  src/viur/core/tasks.py
Labels: hotfix, Priority: High

#1020 fix: `@property` in module causes problems during warmup
  src/viur/core/module.py
Labels: hotfix, Priority: High, python

#1010 fix: Finetuning `ViurTagsSearchAdapter` defaults
  src/viur/core/skeleton.py
Labels: proposal, Priority: Medium, main

#1008 fix: Add check for `db.Key` in `KeyBone.singleValueFromClient`
  src/viur/core/bones/key.py
Labels: hotfix, Priority: High, main

#1023 fix: Improve and refactor `BaseSkel.fromClient()` to handle empty/unset data
  src/viur/core/bones/record.py
  src/viur/core/skeleton.py
Labels: hotfix, Priority: High, refactoring, main

#1029 feat: Support compute for multilang and/or multiple bones
  src/viur/core/bones/base.py
Labels: bug, feature, Priority: High

#969 feat: Improve translations & provide `Translation` module
  src/viur/core/__init__.py
  src/viur/core/config.py
  src/viur/core/i18n.py
  src/viur/core/languages/de.py
  src/viur/core/languages/en.py
  src/viur/core/modules/translation.py
  src/viur/core/render/html/env/viur.py
  src/viur/core/skeleton.py
Labels: feature, Priority: High, refactoring, breaking-changes

#1030 feat: Add and improve check on root node in `Tree` prototype
  src/viur/core/prototypes/tree.py
Labels: feature, Priority: Low

#968 refactor: `Skeleton.fromDB` method
  src/viur/core/skeleton.py
Labels: refactoring, python

#1009 feat: Show project, python- and core-versions on startup
  src/viur/core/__init__.py
Labels: feature

#960 fix: Get rid of the catch all index behavior in vi renderer
  src/viur/core/render/vi/__init__.py
Labels: invalid, Priority: Medium

#1025 refactor: Replace `%`-formattings by f-string (#1025)
  src/viur/core/bones/base.py
  src/viur/core/bones/date.py
  src/viur/core/bones/file.py
  src/viur/core/bones/key.py
  src/viur/core/bones/numeric.py
  src/viur/core/bones/randomslice.py
  src/viur/core/bones/record.py
  src/viur/core/bones/relational.py
  src/viur/core/bones/spatial.py
  src/viur/core/bones/string.py
  src/viur/core/bones/text.py
  src/viur/core/cache.py
  src/viur/core/email.py
  src/viur/core/errors.py
  src/viur/core/i18n.py
  src/viur/core/modules/file.py
  src/viur/core/modules/user.py
  src/viur/core/pagination.py
  src/viur/core/prototypes/list.py
  src/viur/core/prototypes/singleton.py
  src/viur/core/prototypes/tree.py
  src/viur/core/ratelimit.py
  src/viur/core/render/html/env/viur.py
  src/viur/core/render/vi/__init__.py
  src/viur/core/render/vi/user.py
  src/viur/core/render/xml/__init__.py
  src/viur/core/render/xml/default.py
  src/viur/core/request.py
  src/viur/core/securityheaders.py
  src/viur/core/skeleton.py
  src/viur/core/tasks.py
  src/viur/core/utils/__init__.py
Labels: Priority: Low, refactoring, python

#1031 feat: Support for nested modules in `getStructure()`
  src/viur/core/render/vi/__init__.py
Labels: feature, Priority: High

#973 refactor: `Skeleton.toDB` method
  src/viur/core/skeleton.py
Labels: refactoring, python

#1033 fix: Make `UserPassword.pwrecover` ready for action-skels
  src/viur/core/modules/user.py
Labels: Priority: High, refactoring, main

#1036 feat: `clone`-action for `List` and `Tree`, recursive tree cloning
  src/viur/core/prototypes/list.py
  src/viur/core/prototypes/tree.py
Labels: feature, Priority: High

#1034 feat: Provide script configuration in `ModuleConf`
  src/viur/core/languages/de.py
  src/viur/core/modules/moduleconf.py
  src/viur/core/modules/script.py
Labels: Priority: High, main

#1042 fix: Help and comments on `UserPassword.pwrecover`
  src/viur/core/modules/user.py
Labels: Priority: Low, refactoring

#1043 fix: Wrong f-strings introducted by #1025
  src/viur/core/tasks.py
  src/viur/core/utils/__init__.py
Labels: bug(fix), Priority: Critical, python

#1044 fix: customize `iter_bone_value` for `NumericBone`
  src/viur/core/bones/numeric.py
Labels: bug(fix), Priority: High

#995 feat: Collect modules recursivly in `vi/config`
  src/viur/core/render/vi/__init__.py
Labels: feature, Priority: High

#1041 feat: Collect modules recursivly in `read_all_modules`
  src/viur/core/modules/moduleconf.py
Labels: feature, Priority: Medium

#950 fix: compute for relational bones
  src/viur/core/bones/base.py
  src/viur/core/skeleton.py
Labels: bug(fix), Priority: High

#1046 refactor: Modularization of `File`
  src/viur/core/bones/text.py
  src/viur/core/modules/file.py
  src/viur/core/render/html/env/viur.py
  src/viur/core/render/json/default.py
  src/viur/core/utils/__init__.py
  tests/Pipfile
  tests/Pipfile.lock
  tests/main.py
Labels: Priority: Medium, refactoring

#1048 fix: Add missing import in #950
  src/viur/core/bones/base.py
Labels: bug(fix), Priority: Critical, python

#1051 fix: `_validate_request` in `tasks`
  src/viur/core/tasks.py
Labels: bug(fix), Priority: High

#1049 fix: Further refactoring and fixing of `File`-module for #1046
  src/viur/core/bones/text.py
  src/viur/core/modules/file.py
  src/viur/core/render/html/env/viur.py
  src/viur/core/render/json/default.py
  tests/main.py
Labels: bug(fix), Priority: High

#1052 fix: `RelationalBone` locking bug
  src/viur/core/bones/relational.py
Labels: bug(fix), Priority: High, main
