Repository viur-framework/viur-core, pull requests merged in 2024-07, with the labels that each got.

#1203 feat: Render `SelectBone` values in dict-style
  src/viur/core/bones/select.py
  src/viur/core/config.py
Labels: refactoring, viur-meeting, performance, usability

#1192 refactor: Remove `xml` renderer
  src/viur/core/render/__init__.py
  src/viur/core/render/xml/__init__.py
  src/viur/core/render/xml/default.py
  src/viur/core/render/xml/user.py
Labels: proposal, Priority: Medium

#1208 fix: `Session.__delitem__` causes endless recursion
  src/viur/core/session.py
Labels: bug(fix)

#1200 fix: `viur-core-migrate-config` should replace sendinblue and mailjet configs as well
  src/viur/core/scripts/migrate_config.py
Labels: bug(fix), Priority: Low, main

#1077 refactor: `BaseBone.buildDBSort`
  src/viur/core/bones/base.py
  src/viur/core/bones/relational.py
  src/viur/core/bones/string.py
  src/viur/core/utils/parse.py
Labels: feature, Priority: Medium, refactoring, performance

#1213 fix: `RecordBone.getReferencedBlobs` should collect references for all bones
  src/viur/core/bones/record.py
Labels: bug(fix), Priority: Critical

#1209 feat: Add `SpamBone`
  src/viur/core/bones/__init__.py
  src/viur/core/bones/spam.py
  src/viur/core/languages/de.py
Labels: feature, viur-meeting, usability

#1212 refactor: `email`-module/`EmailTransportMailjet` fixes
  Pipfile
  Pipfile.lock
  src/viur/core/email.py
  src/viur/core/requirements.txt
Labels: dependencies, Priority: High, refactoring, main, usability

#1216 feat: Improve email attachments
  src/viur/core/email.py
Labels: feature

#1210 feat: Add `EmailTransportAppengine` as default email transport class
  src/viur/core/email.py
Labels: feature, Priority: High, viur-meeting, main, usability

#1223 feat-fix: Wrap `descr` and `params.category` in `translate` object for auto translating
  src/viur/core/bones/base.py
Labels: bug(fix), Priority: High

#1224 chore: Use `pyproject.toml` as new SSOT packaging system
  Pipfile
  Pipfile.lock
  pyproject.toml
  setup.cfg
  setup.py
  src/viur/core/requirements.txt
Labels: dependencies, Priority: High, refactoring, breaking-changes, requirement
