Repository viur-framework/viur-core, pull requests merged in 2024-10, with the labels that each got.

#1264 refactor: `Skeleton`-API rework
  src/viur/core/bones/base.py
  src/viur/core/bones/file.py
  src/viur/core/i18n.py
  src/viur/core/modules/file.py
  src/viur/core/modules/moduleconf.py
  src/viur/core/modules/script.py
  src/viur/core/modules/translation.py
  src/viur/core/modules/user.py
  src/viur/core/prototypes/list.py
  src/viur/core/prototypes/singleton.py
  src/viur/core/prototypes/tree.py
  src/viur/core/render/html/env/viur.py
  src/viur/core/skeleton.py
Labels: Priority: High, refactoring

#1272 feat: Make custom jinja filter `|fileSize` deprecated
  src/viur/core/render/html/env/viur.py
Labels: feature, Priority: Low

#1271 Fix: Remove urlencode
  src/viur/core/render/html/env/viur.py
Labels: feature, Priority: Medium

#1278 feat: `conf.bone_html_default_allow`
  src/viur/core/bones/text.py
  src/viur/core/config.py
  src/viur/core/modules/moduleconf.py
Labels: feature

#1274 feat: Add support for callable `defaultValue` in `BooleanBone`
  src/viur/core/bones/base.py
  src/viur/core/bones/boolean.py
Labels: bug(fix), feature, Priority: Medium

#1259 feat+refactor: Improved and extended `Skeleton.subskel()`
  src/viur/core/skeleton.py
Labels: proposal, Priority: High, refactoring, requirement, usability

#1281 fix: Calling `db.KeyHelper` with `None` raises a unhandled `NotImplementedError`
  src/viur/core/skeleton.py
Labels: bug(fix), Priority: High

#1282 fix: multiple bones with languages have the wrong default value
  src/viur/core/bones/base.py
Labels: bug(fix), Priority: High

#1286 fix: `SkeletonInstance` must accept `bone_map` and deprecated `clonedBoneMap`
  src/viur/core/skeleton.py
Labels: bug(fix), Priority: High

#1284 fix: Improved signature test on callable `defaultValue`
  src/viur/core/bones/base.py
Labels: bug(fix)

#1277 feat: Load Session only when needed
  src/viur/core/config.py
  src/viur/core/modules/user.py
  src/viur/core/request.py
  src/viur/core/securitykey.py
  src/viur/core/session.py
Labels: feature, Priority: Medium, viur-meeting, performance, python

#1215 feat: Add CORS settings and set CORS header for OPTION CORS(-preflight) requests
  src/viur/core/config.py
  src/viur/core/decorators.py
  src/viur/core/module.py
  src/viur/core/request.py
Labels: feature, Priority: Medium, viur-meeting

#1267 feat: `Skeleton.patch()` for transactional read/write
  src/viur/core/bones/__init__.py
  src/viur/core/bones/base.py
  src/viur/core/skeleton.py
Labels: feature, Priority: High

#1283 chore: Merging of `migrate_config.py` and `viur-2to3.py` into `viur-migrate` tool
  README.md
  pyproject.toml
  src/viur/core/__init__.py
  src/viur/core/scripts/viur_migrate.py
Labels: Priority: High, tools

#1254 feat: `UriBone`
  src/viur/core/bones/__init__.py
  src/viur/core/bones/uri.py
  tests/bones/test_uri_bone.py
Labels: feature, Priority: High, python

#1287 fix: `File.parse_download_url()`: `too many values to unpack`
  CHANGELOG.md
  src/viur/core/modules/file.py
  src/viur/core/version.py
Labels: bug(fix), Priority: High

#1145 feat: Add `serialize_compute` and `unserialize_compute` to `BaseBone`
  src/viur/core/bones/base.py
  src/viur/core/bones/credential.py
  src/viur/core/bones/key.py
  src/viur/core/bones/password.py
Labels: bug(fix), Priority: High

#1081 refactor: `RelationalBone.setBoneValue`
  src/viur/core/bones/relational.py
Labels: Priority: High, refactoring

#1288 fix: `Skeleton.processRemovedRelations` unable to handle empty values
  CHANGELOG.md
  src/viur/core/skeleton.py
  src/viur/core/version.py
Labels: bug(fix), main

#1289 refactor: `Skeleton.patch()`s `db.IsInTransaction`-mode
  src/viur/core/skeleton.py
Labels: refactoring

#1292 fix: Test `user["status"]` at one place
  src/viur/core/modules/user.py
Labels: bug(fix)

#1087 refactor: `relationalBone.serialize()`
  src/viur/core/bones/relational.py
Labels: Priority: High, refactoring

#1294 feat: Introduce `conf.email.sender_default`
  src/viur/core/config.py
  src/viur/core/email.py
Labels: feature, Priority: Medium

#1295 fix: Handle `RefSkel`s in `unserialize_compute` differently
  src/viur/core/bones/base.py
Labels: bug(fix), Priority: High

#1296 fix: `UserSkel.__new__()` cannot be subSkel'ed
  CHANGELOG.md
  src/viur/core/modules/user.py
  src/viur/core/version.py
Labels: bug(fix), Priority: High, main

#1299 fix: `default_order`-code raises `errors.Unauthorized()` on MultiQuery
  CHANGELOG.md
  src/viur/core/prototypes/list.py
  src/viur/core/prototypes/tree.py
Labels: bug(fix), Priority: Critical, main

#1297 fix: `Skeleton.subskel()` and `SkeletonInstance.clone()`
  src/viur/core/skeleton.py
Labels: bug(fix), Priority: High

#1298 fix: Extend `viur_migrate` to further conf keys
  src/viur/core/scripts/viur_migrate.py
Labels: bug(fix), Priority: Medium

#1301 fix: `uploadKey` wrong in `getUploadUrl`
  src/viur/core/modules/file.py
Labels: bug(fix), Priority: High

#1302 refactor: Replace `db.encodeKey` by `str`-cast
  src/viur/core/render/html/default.py
  src/viur/core/render/json/default.py
  src/viur/core/utils/json.py
Labels: Priority: Medium, refactoring

#1304 fix: Add default Param for createRelSkelFromKey
  src/viur/core/bones/relational.py
Labels: bug(fix), Priority: High

#1305 feat: Add `File.get_download_url()`
  src/viur/core/modules/file.py
Labels: feature, Priority: High

#1310 fix: Remove check if logged-in in `UserPassword.login()`
  src/viur/core/modules/user.py
Labels: bug(fix), Priority: High

#1309 feat: Provide a `User.is_active()` function
  src/viur/core/modules/user.py
Labels: feature
