Repository viur-framework/viur-core, pull requests merged in 2024-04, with the labels that each got.

#1129 fix: Pass arguments in `JsonBone.__init__()` to `super()` call
  src/viur/core/bones/json.py
Labels: bug(fix), Priority: Critical

#1126 feat: Implement `translation_key_prefix` for `SelectBone` values
  src/viur/core/bones/__init__.py
  src/viur/core/bones/base.py
  src/viur/core/bones/select.py
  src/viur/core/skeleton.py
Labels: feature, Priority: Medium

#1128 fix: Add param `_call_deferred`
  src/viur/core/tasks.py
Labels: bug(fix), Priority: Critical, python

#1132 fix: Improve `List.default_order` to respect languages config
  src/viur/core/prototypes/list.py
  src/viur/core/prototypes/tree.py
Labels: bug(fix), Priority: High

#1134 fix: target_version was always `None` (used the default version)
  src/viur/core/tasks.py
Labels: bug(fix), Priority: Critical

#1137 fix: Replace old dict `conf` access with attribute access
  src/viur/core/modules/moduleconf.py
  src/viur/core/modules/script.py
Labels: bug(fix), Priority: High

#1136 fix: Avoid `*AbstractSkel`s from being initialized
  src/viur/core/skeleton.py
Labels: bug(fix), Priority: High

#1139 fix: Replace deprecated `utils.getCurrentUser`
  src/viur/core/prototypes/list.py
  src/viur/core/prototypes/tree.py
Labels: Priority: Low, main

#1142 fix: Readd `Stringbone max_length` check
  src/viur/core/bones/string.py
Labels: Priority: High, main

#1144 bug: Add import of `PIL.ImageCms`
  src/viur/core/modules/file.py
Labels: bug(fix), Priority: Critical

#1143 refactor: Move special system arguments for `CallDeferred` in `make_deferred`'s signature
  src/viur/core/tasks.py
Labels: Priority: Low, refactoring, python

#1140 feat Add session `setdefault`
  src/viur/core/session.py
Labels: feature, Priority: Low

#1133 feat: Add `PeriodicTask` can handle `timedelta` as interval
  src/viur/core/config.py
  src/viur/core/email.py
  src/viur/core/modules/file.py
  src/viur/core/ratelimit.py
  src/viur/core/securitykey.py
  src/viur/core/session.py
  src/viur/core/tasks.py
Labels: Priority: Low

#1119 fix: RelationalBone `serialize` add super call
  src/viur/core/bones/relational.py
Labels: bug(fix), Priority: High, main

#1108 feat: Add support for single value and `__default__` for multi-lang bones
  src/viur/core/bones/base.py
Labels: Priority: Low

#1146 fix: Enfore serialized values are always strings in the datastore
  src/viur/core/bones/numeric.py
  src/viur/core/bones/string.py
  tests/bones/test_string_bone.py
  tests/main.py
  tests/test_utils.py
Labels: bug(fix), Priority: High, main
