Repository viur-framework/viur-core, pull requests merged in 2024-05, with the labels that each got.

#1148 fix: `list` should handle unsatisfiable queries
  src/viur/core/prototypes/list.py
  src/viur/core/prototypes/tree.py
Labels: bug(fix), Priority: High, main

#1149 fix: Fix deprecated `parse_bool` call
  src/viur/core/skeleton.py
Labels: Priority: Low, refactoring, main

#1150 feat: Implement `fromClient(amend=True)` feature
  src/viur/core/prototypes/list.py
  src/viur/core/prototypes/singleton.py
  src/viur/core/prototypes/tree.py
  src/viur/core/skeleton.py
Labels: feature, Priority: High, main, performance

#1159 fix: Support `/deploy/admin` folder as well
  src/viur/core/render/vi/__init__.py
Labels: bug(fix), Priority: High, main

#1158 fix: Make `Translation`-module `admin_info` configurable
  src/viur/core/modules/translation.py
Labels: bug(fix), Priority: High, main

#1156 feat: View script by path
  src/viur/core/modules/script.py
Labels: feature, Priority: High, main

#1161 fix: Don't obfuscate any route with character replacements
  src/viur/core/request.py
Labels: bug(fix), main

#1164 Change of LICENSE from LGPL into MIT
  LICENSE
  README.md
  setup.cfg
  src/viur/core/__init__.py
Labels: Priority: High, viur-meeting, main

#1162 feat: Add `EmailTransportMailjet` to `email.py`
  Pipfile
  Pipfile.lock
  setup.cfg
  src/viur/core/email.py
  src/viur/core/requirements.txt
Labels: feature, Priority: Medium, main

#1166 fix: More invalid replacements in `migrate_config.py`
  src/viur/core/scripts/migrate_config.py
Labels: bug(fix), main

#1171 fix: `ViURJsonEncoder` doesn't handle `db.Entity`
  src/viur/core/utils/json.py
  tests/main.py
Labels: bug(fix), Priority: Critical, main

#1175 chore: Drop python 3.10 support
  .github/workflows/python-test.yaml
  Pipfile
  Pipfile.lock
  setup.cfg
  src/viur/core/bones/select.py
  src/viur/core/requirements.txt
Labels: dependencies, Priority: Medium

#1153 refactor: Sub-class `Session` from `db.Entity` to behave `dict`-compliant
  src/viur/core/session.py
Labels: Priority: Medium, refactoring
