Repository viur-framework/viur-core, pull requests merged in 2024-12, with the labels that each got.

#1340 fix: `SkelModule.default_order` generalized
  src/viur/core/prototypes/list.py
  src/viur/core/prototypes/skelmodule.py
  src/viur/core/prototypes/tree.py
  src/viur/core/render/html/env/viur.py
Labels: bug(fix), Priority: High, refactoring

#1345 fix: Lower deprecations for `Skeleton.fromDB/toDB`
  src/viur/core/skeleton.py
Labels: proposal, viur-meeting, annoying

#1344 fix: add `servingurl` to `FileBone`s default `refKeys` setting
  src/viur/core/bones/file.py
  src/viur/core/modules/file.py
Labels: bug(fix), Priority: High, main

#1341 fix+refactor: html-render `getSkel()` and `getList()`
  src/viur/core/render/html/env/viur.py
Labels: bug(fix), security, Priority: High, refactoring

#1346 feat: add more filter-options to `SelectCountryBone`
  src/viur/core/bones/selectcountry.py
Labels: feature, refactoring

#1347 fix: Don't create a CSP nonce if unsafe-inline is enabled
  src/viur/core/request.py
Labels: bug(fix), Priority: High

#1349 feat: Public-files repos and improved rootnodes
  CHANGELOG.md
  src/viur/core/modules/file.py
  src/viur/core/prototypes/tree.py
  src/viur/core/render/json/default.py
  src/viur/core/skeleton.py
  src/viur/core/version.py
Labels: feature, security, Priority: Critical, main, usability

#1350 fix: `FileBone.postSaveHandler` iterates over `None`
  src/viur/core/bones/file.py
Labels: bug(fix), Priority: High

#1351 fix: `SelectBone.singleValueFromClient` doesn't accept `Enum` (backport #1320)
  CHANGELOG.md
  src/viur/core/bones/select.py
  src/viur/core/version.py
Labels: feature, Priority: Medium
