Repository viur-framework/viur-core, pull requests merged in 2024-11, with the labels that each got.

#1314 fix: Add `**kwargs` to skeleton meta classes
  src/viur/core/skeleton.py
Labels: bug(fix), Priority: High

#1312 fix: Add `__set_name__` in `__setattr__` for bones
  src/viur/core/skeleton.py
Labels: bug(fix), Priority: High

#1313 feat: Support enum type
  src/viur/core/module.py
Labels: bug(fix), feature, Priority: High

#1032 feat: Add `scriptor` access flag
  src/viur/core/config.py
  src/viur/core/modules/user.py
Labels: documentation, feature

#1319 fix: Comment out annoying `"final append..."` logs
  src/viur/core/i18n.py
Labels: main, annoying

#1318 fix: Improve ValueError message on invalid `email.transport_class`
  src/viur/core/email.py
Labels: bug(fix), main

#1317 fix: Name `f"server.modules.user.accessright.{right}"` correctly
  src/viur/core/modules/moduleconf.py
  src/viur/core/modules/script.py
  src/viur/core/modules/user.py
Labels: bug(fix), Priority: Low, main

#1321 feat: `SkelModule.structure()` with actions and with access control
  CHANGELOG.md
  src/viur/core/prototypes/list.py
  src/viur/core/prototypes/singleton.py
  src/viur/core/prototypes/tree.py
  src/viur/core/version.py
Labels: Priority: High

#1328 fix: `File.parse_download_url()` handles dlpath wrong
  src/viur/core/modules/file.py
Labels: bug(fix), Priority: High

#1323 feat: Public translations interface
  CHANGELOG.md
  src/viur/core/i18n.py
  src/viur/core/modules/translation.py
Labels: feature, Priority: High

#1326 fix: `SpamBone()` consumes default iterator once
  src/viur/core/bones/spam.py
Labels: bug(fix), Priority: High, main

#1324 fix: `SpamBone`'s descr not available without session
  src/viur/core/bones/base.py
  src/viur/core/bones/spam.py
Labels: bug(fix), Priority: High, main

#1320 fix: `SelectBone.singleValueFromClient()` can't handle `Enum` values
  src/viur/core/bones/select.py
Labels: bug(fix), main

#1329 fix: `JsonBone` validate `object` and `list` too
  src/viur/core/bones/json.py
Labels: bug(fix), Priority: Medium

#1333 fix: Store written db_obj in `toDB` on source skel
  src/viur/core/skeleton.py
Labels: bug(fix), Priority: Critical

#1332 fix: Revert changes from #1323
  src/viur/core/i18n.py
Labels: bug(fix), Priority: Critical

#1331 fix: `User.is_active()` without status-bone
  src/viur/core/modules/user.py
Labels: bug(fix)

#1330 feat: Provide `ignore`-parameter for `Skeleton.fromClient`
  src/viur/core/skeleton.py
Labels: feature, security, Priority: High, main

#1334 fix: Return a `list` instead of `None` in `RelationalBone.relskels_from_keys`
  src/viur/core/bones/relational.py
Labels: bug(fix), Priority: High

#1335 fix: Allow `list` in `SpatialBone` `setBoneValue`
  src/viur/core/bones/spatial.py
Labels: bug(fix), Priority: High

#1336 fix: Correct `translation_key_prefix_skeleton_bonename` and `translation_key_prefix_bonename`
  src/viur/core/bones/select.py
Labels: bug(fix), invalid, Priority: Medium, annoying
