Repository viur-framework/viur-core, pull requests merged in 2025-06, with the labels that each got.

#1454 feat: `ImageBone` (and some little splitting of skeleton.py)
  src/viur/core/bones/__init__.py
  src/viur/core/bones/image.py
  src/viur/core/config.py
  src/viur/core/modules/file.py
  src/viur/core/skeleton.py
  src/viur/core/skeleton/__init__.py
  src/viur/core/skeleton/adapter.py
  src/viur/core/skeleton/instance.py
  src/viur/core/skeleton/meta.py
  src/viur/core/skeleton/relskel.py
  src/viur/core/skeleton/skeleton.py
  src/viur/core/skeleton/tasks.py
  src/viur/core/skeleton/utils.py
Labels: feature, discussion, Priority: High, refactoring, accessibility

#1498 ref: Replace old db calls
  src/viur/core/i18n.py
  src/viur/core/skeleton/skeleton.py
Labels: Priority: Medium, annoying

#1499 fix: `ensureDerived` imports
  src/viur/core/bones/file.py
Labels: Priority: High

#1500 fix: Add missing imports for skeleton
  src/viur/core/skeleton/instance.py
  src/viur/core/skeleton/skeleton.py
Labels: bug(fix), Priority: High

#1501 ref: Remove `print` in `key_helper`
  src/viur/core/db/utils.py
Labels: annoying

#1460 fix: `dump` does not yield anything if there's no pattern filter given
  src/viur/core/modules/translation.py
Labels: bug(fix), Priority: High

#1508 fix: Update skeleton write update relations
  src/viur/core/skeleton/skeleton.py
Labels: Priority: High
