Repository viur-framework/viur-core, pull requests merged in 2025-05, with the labels that each got.

#1471 fix: `prototypes.List` shall default to `addSkel` on cloning
  src/viur/core/prototypes/list.py
Labels: bug(fix), main

#1459 refactor: Deprecate setDefaultLanguage
  src/viur/core/__init__.py
Labels: refactoring

#1465 feat: Add retries for `db.run_in_transaction`
  src/viur/core/db/transport.py
Labels: feature, Priority: Medium

#1464 feat: Move `db.conf` to `viur.core.config`
  src/viur/core/cache.py
  src/viur/core/config.py
  src/viur/core/db/cache.py
  src/viur/core/db/config.py
  src/viur/core/db/query.py
  src/viur/core/db/transport.py
Labels: feature

#1293 refactor: File-module reference should use instance
  src/viur/core/modules/file.py
  src/viur/core/render/html/env/viur.py
  src/viur/core/utils/__init__.py
Labels: Priority: Medium, refactoring

#1475 chore: Update dependency gunicorn to >=23
  pyproject.toml
Labels: dependencies

#1482 fix: Avoid sending doubled Set-Cookie header
  src/viur/core/session.py
Labels: bug(fix)

#1480 fix: Improve auth_userpassword login failure detection
  src/viur/core/bones/password.py
  src/viur/core/modules/user.py
Labels: bug(fix), refactoring, main

#1441 feat: History module
  pyproject.toml
  src/viur/core/__init__.py
  src/viur/core/config.py
  src/viur/core/modules/history.py
Labels: feature, proposal

#1493 feat: Pass `create` param in `Singleton.getContents()` to `Skeleton.read()`
  src/viur/core/prototypes/singleton.py
Labels: feature, Priority: Medium
