Repository viur-framework/viur-core, pull requests merged in 2025-08, with the labels that each got.

#1535 feat: Add `changed_fields` in `History`-Module
  src/viur/core/modules/history.py
Labels: feature

#1445 feat: Allow `db.Key` in the `index`-method
  src/viur/core/module.py
  src/viur/core/prototypes/list.py
Labels: feature, Priority: High

#1538 fix: `User.is_admin()` to determine User admin privileges
  src/viur/core/modules/user.py
Labels: bug(fix), breaking-changes, annoying

#1541 fix+refactor: `Tree.move()`
  src/viur/core/prototypes/tree.py
Labels: bug(fix), refactoring

#1511 fix: Remove renderPreparation of nested skeletons
  src/viur/core/render/html/default.py
  src/viur/core/skeleton.py
  src/viur/core/utils/__init__.py
Labels: bug(fix), Priority: High, annoying
