Repository viur-framework/viur-core, pull requests merged in 2025-01, with the labels that each got.

#1357 fix: Regression from `canView()` refactoring
  src/viur/core/prototypes/list.py
  src/viur/core/prototypes/tree.py
Labels: bug(fix), main

#1358 fix: `BooleanBone.setBoneValue` doesn't respect language
  src/viur/core/bones/base.py
  src/viur/core/bones/boolean.py
Labels: bug(fix)

#1362 fix: `FileLeafSkel._inject_serving_url()` is the better choice
  src/viur/core/modules/file.py
Labels: bug(fix)

#1365 feat: Provide default `index`-function for `Tree` and `Singleton`
  src/viur/core/prototypes/singleton.py
  src/viur/core/prototypes/tree.py
Labels: feature, Priority: Medium

#1371 fix: Render bones which are `readOnly=True` not as `required=True`
  src/viur/core/bones/base.py
Labels: annoying

#1370 fix: Ensure derives are generated in `FileBone` inside a `RecordBone` too
  src/viur/core/bones/base.py
  src/viur/core/bones/file.py
  src/viur/core/bones/record.py
  src/viur/core/bones/relational.py
Labels: bug(fix), Priority: High

#1373 fix: `SkelModule` not able to handle empty index definitions
  src/viur/core/prototypes/skelmodule.py
Labels: bug(fix)

#1372 doc: Fix `SyntaxWarning: invalid escape sequence '\*'`
  src/viur/core/skeleton.py
Labels: annoying

#1374 fix: `errors` not marked as a reserved word
  src/viur/core/skeleton.py
Labels: bug(fix)

#1375 fix: Provide bone name with assertion message
  src/viur/core/bones/base.py
Labels: bug(fix), annoying

#1367 fix: determine a better path for a new `TranslateSkel`
  src/viur/core/i18n.py
  src/viur/core/render/html/env/viur.py
Labels: bug(fix), Priority: Medium

#1377 fix: skip `cached_property` in `Module._update_methods`
  src/viur/core/module.py
Labels: bug(fix), Priority: Medium, performance

#1380 feat: Provide `add_or_edit` root-only endpoint for importers
  src/viur/core/prototypes/skelmodule.py
  src/viur/core/prototypes/tree.py
Labels: feature, Priority: High, main

#1378 fix: a `not caseSensitive` bone should lock the lower value
  src/viur/core/bones/base.py
  src/viur/core/bones/string.py
Labels: bug(fix), invalid, Priority: High

#1382 fix: Add check for preflight requests in closed_systems
  src/viur/core/request.py
Labels: bug(fix), Priority: High

#1388 fix: Improve and standardize `Script` module `vfuncs`
  src/viur/core/modules/script.py
Labels: bug(fix)

#1393 fix: Improve error reporting for unknown `RelationalBone` kinds
  src/viur/core/bones/relational.py
Labels: bug(fix), annoying

#1392 refactor: `RelationalBone.refresh()`
  src/viur/core/bones/relational.py
  src/viur/core/skeleton.py
Labels: bug(fix), refactoring, main

#1395 fix: Email methods has been renamed
  src/viur/core/__init__.py
  src/viur/core/config.py
  src/viur/core/email.py
  src/viur/core/modules/user.py
  src/viur/core/scripts/viur_migrate.py
  src/viur/core/tasks.py
Labels: Priority: High, refactoring
