Repository viur-framework/viur-core, pull requests merged in 2025-04, with the labels that each got.

#1452 fix: Further `Translation.dump()` clean-up
  src/viur/core/modules/translation.py
Labels: bug(fix), refactoring

#1449 fix: `add_or_edit` edits entries with empty skeleton
  CHANGELOG.md
  src/viur/core/prototypes/skelmodule.py
  src/viur/core/prototypes/tree.py
  src/viur/core/version.py
Labels: bug(fix), Priority: Critical

#1455 fix: Change adjust_kind to boolean
  src/viur/core/prototypes/skelmodule.py
  src/viur/core/prototypes/tree.py
Labels: Priority: Medium

#1453 fix: `RecordBone` and prefix substitution
  src/viur/core/bones/base.py
  src/viur/core/bones/record.py
Labels: bug(fix), Priority: High

#1448 feat: Allow `timedelta` for `session_life_time`
  src/viur/core/config.py
  src/viur/core/session.py
Labels: feature

#1457 feat: Apply `escape_html`-settings in `StringBone.refresh()`
  src/viur/core/bones/string.py
Labels: Priority: Medium

#1463 fix: Fix `access_log` for `db.delete`
  src/viur/core/db/transport.py
Labels: bug(fix)

#1458 fix: Update user's data in session on `user/edit`
  src/viur/core/modules/user.py
Labels: bug(fix), Priority: High

#1462 fix: `RelationalBone` `multiple`-`using` case.
  src/viur/core/bones/relational.py
Labels: bug(fix)

#1466 fix: Add a `Key` in `access_log`
  src/viur/core/db/transport.py
Labels: bug(fix), Priority: Medium
