Repository viur-framework/viur-core, pull requests merged in 2025-03, with the labels that each got.

#1437 fix: `NumericBone.singleValueUnserialize` can't handle `str`
  src/viur/core/bones/numeric.py
Labels: bug(fix)

#1439 fix: `File.onEdit()` executes "leaf"-related stuff regardless of the `skelType`
  src/viur/core/modules/file.py
Labels: bug(fix), Priority: High, annoying

#1438 feat: Implement `on_delete` hook/event for sessions
  src/viur/core/session.py
Labels: feature

#1415 feat: Evaluate `x-viur-bonelist` on default `viewSkel()` (light-version)
  src/viur/core/prototypes/list.py
  src/viur/core/prototypes/singleton.py
  src/viur/core/prototypes/skelmodule.py
Labels: feature, Priority: High, main

#1413 chore: Disable all compatibility flags by default
  src/viur/core/config.py
Labels: Priority: Low

#1442 fix: `singleValueUnserialize` is now working more stable
  src/viur/core/bones/numeric.py
  tests/bones/test_numeric_bone.py
Labels: bug(fix), Priority: Critical

#1440 feat: Add `DeleteEntitiesIter` for `viur-transactionmarker`
  src/viur/core/tasks.py
Labels: feature, Priority: Low

#1443 fix: don't compute a bone in a not existing relation
  src/viur/core/bones/base.py
  src/viur/core/skeleton.py
Labels: bug(fix), Priority: Critical

#1364 fix: General fixing and clean-up on `translate()`
  src/viur/core/bones/select.py
  src/viur/core/config.py
  src/viur/core/errors.py
  src/viur/core/i18n.py
  src/viur/core/languages/de.py
  src/viur/core/languages/en.py
  src/viur/core/modules/moduleconf.py
  src/viur/core/modules/script.py
  src/viur/core/modules/translation.py
  src/viur/core/modules/user.py
Labels: bug(fix), proposal, Priority: High, refactoring, annoying

#1444 fix: Better handling of invalid blob keys in `File.download()`
  src/viur/core/modules/file.py
Labels: bug(fix), Priority: Medium
