Repository viur-framework/viur-core, pull requests merged in 2025-02, with the labels that each got.

#1391 feat: Add missing `onAdd` and `onAdded` calls in `File` module and implement `set_image_meta`
  src/viur/core/modules/file.py
Labels: feature, Priority: Medium, viur-meeting

#1407 fix: `BooleanBone.refresh()` doesn't respect language
  src/viur/core/bones/boolean.py
  src/viur/core/skeleton.py
Labels: bug(fix), Priority: High, main, annoying

#1404 fix: `FileBone.refresh()` should fix `serving_url`
  src/viur/core/bones/file.py
  src/viur/core/bones/relational.py
Labels: bug(fix), Priority: High, main, annoying

#1401 feat: Implement `CloneBehavior` + `CloneStrategy` for a bone individual clone behavior
  src/viur/core/bones/__init__.py
  src/viur/core/bones/base.py
  src/viur/core/bones/sortindex.py
  src/viur/core/prototypes/list.py
  src/viur/core/prototypes/tree.py
  src/viur/core/skeleton.py
Labels: bug(fix), Priority: High

#1406 fix: Load user in a deferred task
  src/viur/core/modules/user.py
  src/viur/core/tasks.py
Labels: bug(fix), Priority: Critical, Priority: High

#1408 fix: Make translations usable
  src/viur/core/bones/string.py
  src/viur/core/modules/translation.py
Labels: bug(fix), Priority: High, annoying

#1409 fix: `conf.i18n.add_missing_translations` the right way
  src/viur/core/i18n.py
Labels: bug(fix), Priority: High, annoying

#1394 fix: Custom decorators do not work
  src/viur/core/decorators.py
  src/viur/core/module.py
Labels: bug(fix), feature, Priority: High

#1410 fix: `Tree.add_or_edit()` should require for parententry
  src/viur/core/prototypes/tree.py
Labels: bug(fix)

#1411 chore: Enforce config strict mode
  src/viur/core/config.py
Labels: Priority: Medium

#1414 fix: Replace deprecated `ensureOwnModuleRootNode` with `rootnodeSkel`
  src/viur/core/modules/page.py
  src/viur/core/modules/script.py
Labels: bug(fix), Priority: Medium

#1418 fix: Keep `None` in `BooleanBones`
  src/viur/core/bones/boolean.py
Labels: bug(fix)

#1419 fix: Hotfix for decorator `@skey` introduced by #1394
  src/viur/core/decorators.py
  src/viur/core/module.py
Labels: bug(fix), Priority: High, main

#1420 fix: Hotfix for #1391: missing skeltype-check
  src/viur/core/modules/file.py
Labels: bug(fix), Priority: High, main

#1421 fix: `Skeleton.write()` returns full skeleton
  src/viur/core/skeleton.py
Labels: bug(fix), Priority: Critical

#1425 fix: `NumericBone` ignores precision on read & write
  src/viur/core/bones/numeric.py
Labels: bug(fix), Priority: Medium

#1428 perf: Add check to avoid redundant `ensueDerived` calls
  src/viur/core/bones/file.py
  src/viur/core/skeleton.py
Labels: Priority: Low, performance

#1430 fix: Make `skeleton.listKnownSkeletons` always sorted
  src/viur/core/skeleton.py
Labels: bug(fix), main

#1434 feat: Implement `conf.tasks_default_queues`
  src/viur/core/config.py
  src/viur/core/tasks.py
Labels: feature

#1433 chore: Remove legacy `viur-queued-tasks` code
  src/viur/core/tasks.py
Labels: invalid, Priority: Low
