Repository viur-framework/viur-core, pull requests merged in 2025-07, with the labels that each got.

#1308 feat: extend `File.write()` to accept a `rootnode` and `folder`
  src/viur/core/modules/file.py
Labels: feature, Priority: Medium

#1516 chore: Lift viur-core to Python >= 3.12
  .github/workflows/python-test.yaml
  CONTRIBUTING.md
  pyproject.toml
Labels: dependencies, Priority: High, python, requirement, usability

#1000 feat+refactor: `skel.dump()` for simplified value serialization (replacement for JSON value rendering)
  src/viur/core/bones/base.py
  src/viur/core/bones/file.py
  src/viur/core/bones/password.py
  src/viur/core/bones/record.py
  src/viur/core/bones/relational.py
  src/viur/core/render/json/default.py
  src/viur/core/skeleton/instance.py
Labels: refactoring, python

#1525 fix+refactor: `_tasks/list` and `SkelList`
  src/viur/core/db/query.py
  src/viur/core/render/json/default.py
  src/viur/core/skeleton/instance.py
  src/viur/core/skeleton/utils.py
  src/viur/core/tasks.py
Labels: bug(fix), Priority: High, refactoring

#1520 refactor: Add `Database` `ConfigType`
  src/viur/core/cache.py
  src/viur/core/config.py
  src/viur/core/db/cache.py
  src/viur/core/db/config.py
  src/viur/core/db/query.py
  src/viur/core/db/transport.py
  src/viur/core/db/types.py
Labels: refactoring

#1417 refactor: `RelationalBone.fromClient()`
  src/viur/core/bones/relational.py
Labels: Priority: High, refactoring, performance

#1530 docs(cicd): Update to Python 3.13 and latest sphinx
  docs/Pipfile
  docs/Pipfile.lock
  docs/requirements.txt
  docs/rtdtemplate/layout.html
  docs/rtdtemplate/static/css/theme.css
  docs/rtdtemplate/static/css/theme.min.css
  src/viur/core/bones/uri.py
Labels: bug(fix), dependencies

#1531 fix: `History`-module improvements
  src/viur/core/__init__.py
  src/viur/core/modules/history.py
Labels: bug(fix)

#1526 fix: `otp_timedrift` and its updating is broken and outdated
  src/viur/core/modules/user.py
Labels: bug(fix)

#1533 fix: Make `#` a safe character for redirects
  src/viur/core/request.py
Labels: bug(fix)
